# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from enum import Enum
from typing import Any, Dict

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)
from sellapp_sdk.common.models.enable_or_disable_payment_method_response_value_200_application_json_property_data_property_required_input_item_type import (
    EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType,
)

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem",
    "required": ["name", "type", "required", "secret"],
    "properties": {
        "name": {"kind": "primitive", "type": "string"},
        "type": {
            "kind": "enum",
            "values": ["string", "enum", "boolean", "array", "decimal"],
        },
        "required": {"kind": "primitive", "type": "boolean"},
        "secret": {"kind": "primitive", "type": "boolean"},
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem",
    "required": ["name", "type", "required", "secret"],
    "properties": {
        "name": {"kind": "primitive", "type": "string"},
        "type": {
            "kind": "enum",
            "values": ["string", "enum", "boolean", "array", "decimal"],
        },
        "required": {"kind": "primitive", "type": "boolean"},
        "secret": {"kind": "primitive", "type": "boolean"},
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem:
    """Enable Or Disable Payment Method Response Value200Application Json Property Data Property Required Input Item model."""

    name: str
    type: EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType
    required: bool
    secret: bool
    """When true, the corresponding setup value is write-only and is never returned by SellApp."""
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                name=data["name"],
                type=EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType(
                    data["type"]
                ),
                required=data["required"],
                secret=data["secret"],
                additional_properties=_preserve_unknown_fields(
                    data, ["name", "type", "required", "secret"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem",
                e,
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        _domain_data["name"] = self.name
        _domain_data["type"] = self.type
        _domain_data["required"] = self.required
        _domain_data["secret"] = self.secret
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        result["name"] = self.name
        result["type"] = self.type.value if isinstance(self.type, Enum) else self.type
        result["required"] = self.required
        result["secret"] = self.secret
        return result
