# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .archive_cashback_rule_response_value_200_application_json_property_data import (
    ArchiveCashbackRuleResponseValue200ApplicationJsonPropertyData,
)

UpdateCashbackRuleResponseValue200ApplicationJsonPropertyData: TypeAlias = (
    ArchiveCashbackRuleResponseValue200ApplicationJsonPropertyData
)
