# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from sellapp_sdk.common.models.sdk_add_products_to_group_response_value_200_application_json import (
    SdkAddProductsToGroupResponseValue200ApplicationJson,
)

SdkAttachBundleItemsResponseValue200ApplicationJson: TypeAlias = (
    SdkAddProductsToGroupResponseValue200ApplicationJson
)
