# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from sellapp_sdk.common.models.create_add_on_draft_response_value_201_application_json_property_data_property_variants_item import (
    CreateAddOnDraftResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem,
)

GetAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem: TypeAlias = (
    CreateAddOnDraftResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem
)
