# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from enum import Enum
from typing import Any, Dict, Literal

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)
from sellapp_sdk.common.models.send_test_webhook_response_value_200_application_json_property_data_event import (
    SendTestWebhookResponseValue200ApplicationJsonPropertyDataEvent,
)

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "SendTestWebhookResponseValue200ApplicationJsonPropertyData",
    "required": ["channel_id", "event", "status"],
    "properties": {
        "channel_id": {"kind": "primitive", "type": "string", "format": "uuid"},
        "event": {
            "kind": "enum",
            "values": [
                "booking.cancelled",
                "booking.rescheduled",
                "cash_app.payment_requires_attention",
                "charge.completed",
                "charge.created",
                "charge.disputed",
                "charge.partial_paid",
                "charge.review",
                "feedback.created",
                "order.completed",
                "order.created",
                "order.disputed",
                "order.manual_payment_completed",
                "order.paid",
                "order.partial_paid",
                "product.created",
                "product.trashed",
                "product.updated",
                "subscription.cancelled",
                "subscription.created",
                "subscription.renewed",
                "ticket_message.created",
                "variant.created",
                "variant.sold_out",
                "variant.updated",
            ],
        },
        "status": {"kind": "literal", "value": "delivered"},
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "SendTestWebhookResponseValue200ApplicationJsonPropertyData",
    "required": ["channel_id", "event", "status"],
    "properties": {
        "channel_id": {"kind": "primitive", "type": "string", "format": "uuid"},
        "event": {
            "kind": "enum",
            "values": [
                "booking.cancelled",
                "booking.rescheduled",
                "cash_app.payment_requires_attention",
                "charge.completed",
                "charge.created",
                "charge.disputed",
                "charge.partial_paid",
                "charge.review",
                "feedback.created",
                "order.completed",
                "order.created",
                "order.disputed",
                "order.manual_payment_completed",
                "order.paid",
                "order.partial_paid",
                "product.created",
                "product.trashed",
                "product.updated",
                "subscription.cancelled",
                "subscription.created",
                "subscription.renewed",
                "ticket_message.created",
                "variant.created",
                "variant.sold_out",
                "variant.updated",
            ],
        },
        "status": {"kind": "literal", "value": "delivered"},
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class SendTestWebhookResponseValue200ApplicationJsonPropertyData:
    """Send Test Webhook Response Value200Application Json Property Data model."""

    channel_id: str
    event: SendTestWebhookResponseValue200ApplicationJsonPropertyDataEvent
    """Public event name used by channel configuration, search, tests, and delivered webhook payloads."""
    status: Literal["delivered"]
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> SendTestWebhookResponseValue200ApplicationJsonPropertyData:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                channel_id=data["channel_id"],
                event=SendTestWebhookResponseValue200ApplicationJsonPropertyDataEvent(
                    data["event"]
                ),
                status=data.get("status", "delivered"),
                additional_properties=_preserve_unknown_fields(
                    data, ["channel_id", "event", "status"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "SendTestWebhookResponseValue200ApplicationJsonPropertyData", e
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        _domain_data["channel_id"] = self.channel_id
        _domain_data["event"] = self.event
        _domain_data["status"] = self.status
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        result["channel_id"] = self.channel_id
        result["event"] = (
            self.event.value if isinstance(self.event, Enum) else self.event
        )
        result["status"] = self.status
        return result
