# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from .._base_client import WithRawResponse

if TYPE_CHECKING:
    from .._client import AsyncSellAppClient, SellAppClient

from .._pagination import AsyncPage, SyncPage
from .._types import NOT_GIVEN, NotGiven, RequestOptions, _validate_model
from .models import (
    ListVariantDeliverableFilesResponseValue200ApplicationJsonPropertyDataItem,
    SdkGetVariantDeliverableFileResponseValue200ApplicationJson,
    SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson,
    SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson,
    SdkUploadVariantDeliverableFileResponseValue201ApplicationJson,
)


class VariantDeliverableFiles:
    """Variant Deliverable Files API resources."""

    def __init__(self, client: SellAppClient) -> None:
        self._client = client
        self.with_raw_response = WithRawResponse(self)

    def list(
        self,
        product: str,
        variant: int,
        *,
        limit: int | None = None,
        before: str | None = None,
        after: str | None = None,
        order: str | None = None,
        page: int | None = None,
        request_options: RequestOptions | None = None,
    ) -> SyncPage[
        ListVariantDeliverableFilesResponseValue200ApplicationJsonPropertyDataItem
    ]:
        """List variant deliverable files

        List variant deliverable files. Requires the listing Sanctum ability. Lists managed files without revealing storage keys. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            limit: Number of items to return per page. Defaults to `15`.
            before: The before.
            after: The after.
            order: The order.
            page: Page number to return. Defaults to `1`.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SyncPage[ListVariantDeliverableFilesResponseValue200ApplicationJsonPropertyDataItem]

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "listVariantDeliverableFiles",
        }
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order,
                "page": page,
            }.items()
            if v is not None
        }
        return self._client.request_page(
            method="get",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
            ),
            model=ListVariantDeliverableFilesResponseValue200ApplicationJsonPropertyDataItem,
            params=params,
            request_options=request_options,
        )

    def upload(
        self,
        product: str,
        variant: int,
        *,
        file: bytes,
        folder_id: int | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> SdkUploadVariantDeliverableFileResponseValue201ApplicationJson:
        """Upload a variant deliverable file

        Upload a variant deliverable file. Requires the listing Sanctum ability. Accepts an uploaded file, stores it under a server-generated key, and queues the durable move after commit. Uploads may be staged before DOWNLOADABLE is activated; inactive pending files are retained temporarily and scheduled for cleanup if activation is abandoned. Client-supplied storage paths are not accepted. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The file.
            folder_id: The folder id.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkUploadVariantDeliverableFileResponseValue201ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "form-data",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "uploadVariantDeliverableFile",
        }
        body: dict[str, Any] = {
            "file": file,
        }
        if not isinstance(folder_id, NotGiven):
            body["folder_id"] = folder_id
        _validate_model(
            body,
            {
                "name": "SdkUploadVariantDeliverableFileRequestMultipartFormData",
                "required": ["file"],
                "properties": {
                    "file": {"kind": "primitive", "type": "string", "format": "binary"},
                    "folder_id": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        multipart_files: dict[str, Any] = {}
        if "file" in body:
            multipart_files["file"] = body.pop("file")
        request_options = {
            **(request_options or {}),
            "files": {
                **multipart_files,
                **((request_options or {}).get("files") or {}),
            },
        }
        return self._client.request(
            method="post",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
            ),
            body=body,
            model=SdkUploadVariantDeliverableFileResponseValue201ApplicationJson,
            request_options=request_options,
        )

    def get(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        request_options: RequestOptions | None = None,
    ) -> SdkGetVariantDeliverableFileResponseValue200ApplicationJson:
        """Retrieve a variant deliverable file

        Retrieve a variant deliverable file. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkGetVariantDeliverableFileResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "getVariantDeliverableFile",
        }
        return self._client.request(
            method="get",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            model=SdkGetVariantDeliverableFileResponseValue200ApplicationJson,
            request_options=request_options,
        )

    def replace(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        custom_name: str | None | NotGiven = NOT_GIVEN,
        folder_id: int | None | NotGiven = NOT_GIVEN,
        watermark: bool | None = None,
        max_downloads: int | None | NotGiven = NOT_GIVEN,
        limit_to_purchase_ip: bool | None = None,
        request_options: RequestOptions | None = None,
    ) -> SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson:
        """Replace variant deliverable file settings

        Replace variant deliverable file settings. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            custom_name: The custom name.
            folder_id: The folder id.
            watermark: The watermark.
            max_downloads: The max downloads.
            limit_to_purchase_ip: The limit to purchase ip.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "replaceVariantDeliverableFileSettings",
        }
        body: dict[str, Any] = {
            k: v
            for k, v in {
                "watermark": watermark,
                "limit_to_purchase_ip": limit_to_purchase_ip,
            }.items()
            if v is not None
        }
        if not isinstance(custom_name, NotGiven):
            body["custom_name"] = custom_name
        if not isinstance(folder_id, NotGiven):
            body["folder_id"] = folder_id
        if not isinstance(max_downloads, NotGiven):
            body["max_downloads"] = max_downloads
        _validate_model(
            body,
            {
                "name": "SdkReplaceVariantDeliverableFileSettingsRequestApplicationJson",
                "required": [],
                "properties": {
                    "custom_name": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "string"},
                    },
                    "folder_id": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "watermark": {"kind": "primitive", "type": "boolean"},
                    "max_downloads": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "limit_to_purchase_ip": {"kind": "primitive", "type": "boolean"},
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return self._client.request(
            method="put",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            body=body,
            model=SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson,
            request_options=request_options,
        )

    def update(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        custom_name: str | None | NotGiven = NOT_GIVEN,
        folder_id: int | None | NotGiven = NOT_GIVEN,
        watermark: bool | None = None,
        max_downloads: int | None | NotGiven = NOT_GIVEN,
        limit_to_purchase_ip: bool | None = None,
        request_options: RequestOptions | None = None,
    ) -> SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson:
        """Update a variant deliverable file

        Update a variant deliverable file. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            custom_name: The custom name.
            folder_id: The folder id.
            watermark: The watermark.
            max_downloads: The max downloads.
            limit_to_purchase_ip: The limit to purchase ip.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "updateVariantDeliverableFile",
        }
        body: dict[str, Any] = {
            k: v
            for k, v in {
                "watermark": watermark,
                "limit_to_purchase_ip": limit_to_purchase_ip,
            }.items()
            if v is not None
        }
        if not isinstance(custom_name, NotGiven):
            body["custom_name"] = custom_name
        if not isinstance(folder_id, NotGiven):
            body["folder_id"] = folder_id
        if not isinstance(max_downloads, NotGiven):
            body["max_downloads"] = max_downloads
        _validate_model(
            body,
            {
                "name": "SdkUpdateVariantDeliverableFileRequestApplicationJson",
                "required": [],
                "properties": {
                    "custom_name": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "string"},
                    },
                    "folder_id": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "watermark": {"kind": "primitive", "type": "boolean"},
                    "max_downloads": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "limit_to_purchase_ip": {"kind": "primitive", "type": "boolean"},
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return self._client.request(
            method="patch",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            body=body,
            model=SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson,
            request_options=request_options,
        )

    def delete(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Delete a variant deliverable file

        Delete a variant deliverable file. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "deleteVariantDeliverableFile",
        }
        self._client.request(
            method="delete",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            request_options=request_options,
        )


class AsyncVariantDeliverableFiles:
    """Variant Deliverable Files API resources (async)."""

    def __init__(self, client: AsyncSellAppClient) -> None:
        self._client = client
        self.with_raw_response = WithRawResponse(self)

    async def list(
        self,
        product: str,
        variant: int,
        *,
        limit: int | None = None,
        before: str | None = None,
        after: str | None = None,
        order: str | None = None,
        page: int | None = None,
        request_options: RequestOptions | None = None,
    ) -> AsyncPage[
        ListVariantDeliverableFilesResponseValue200ApplicationJsonPropertyDataItem
    ]:
        """List variant deliverable files

        List variant deliverable files. Requires the listing Sanctum ability. Lists managed files without revealing storage keys. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            limit: Number of items to return per page. Defaults to `15`.
            before: The before.
            after: The after.
            order: The order.
            page: Page number to return. Defaults to `1`.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            AsyncPage[ListVariantDeliverableFilesResponseValue200ApplicationJsonPropertyDataItem]

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "listVariantDeliverableFiles",
        }
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order,
                "page": page,
            }.items()
            if v is not None
        }
        return await self._client.request_page(
            method="get",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
            ),
            model=ListVariantDeliverableFilesResponseValue200ApplicationJsonPropertyDataItem,
            params=params,
            request_options=request_options,
        )

    async def upload(
        self,
        product: str,
        variant: int,
        *,
        file: bytes,
        folder_id: int | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> SdkUploadVariantDeliverableFileResponseValue201ApplicationJson:
        """Upload a variant deliverable file

        Upload a variant deliverable file. Requires the listing Sanctum ability. Accepts an uploaded file, stores it under a server-generated key, and queues the durable move after commit. Uploads may be staged before DOWNLOADABLE is activated; inactive pending files are retained temporarily and scheduled for cleanup if activation is abandoned. Client-supplied storage paths are not accepted. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The file.
            folder_id: The folder id.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkUploadVariantDeliverableFileResponseValue201ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "form-data",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "uploadVariantDeliverableFile",
        }
        body: dict[str, Any] = {
            "file": file,
        }
        if not isinstance(folder_id, NotGiven):
            body["folder_id"] = folder_id
        _validate_model(
            body,
            {
                "name": "SdkUploadVariantDeliverableFileRequestMultipartFormData",
                "required": ["file"],
                "properties": {
                    "file": {"kind": "primitive", "type": "string", "format": "binary"},
                    "folder_id": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        multipart_files: dict[str, Any] = {}
        if "file" in body:
            multipart_files["file"] = body.pop("file")
        request_options = {
            **(request_options or {}),
            "files": {
                **multipart_files,
                **((request_options or {}).get("files") or {}),
            },
        }
        return await self._client.request(
            method="post",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
            ),
            body=body,
            model=SdkUploadVariantDeliverableFileResponseValue201ApplicationJson,
            request_options=request_options,
        )

    async def get(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        request_options: RequestOptions | None = None,
    ) -> SdkGetVariantDeliverableFileResponseValue200ApplicationJson:
        """Retrieve a variant deliverable file

        Retrieve a variant deliverable file. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkGetVariantDeliverableFileResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "getVariantDeliverableFile",
        }
        return await self._client.request(
            method="get",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            model=SdkGetVariantDeliverableFileResponseValue200ApplicationJson,
            request_options=request_options,
        )

    async def replace(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        custom_name: str | None | NotGiven = NOT_GIVEN,
        folder_id: int | None | NotGiven = NOT_GIVEN,
        watermark: bool | None = None,
        max_downloads: int | None | NotGiven = NOT_GIVEN,
        limit_to_purchase_ip: bool | None = None,
        request_options: RequestOptions | None = None,
    ) -> SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson:
        """Replace variant deliverable file settings

        Replace variant deliverable file settings. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            custom_name: The custom name.
            folder_id: The folder id.
            watermark: The watermark.
            max_downloads: The max downloads.
            limit_to_purchase_ip: The limit to purchase ip.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "replaceVariantDeliverableFileSettings",
        }
        body: dict[str, Any] = {
            k: v
            for k, v in {
                "watermark": watermark,
                "limit_to_purchase_ip": limit_to_purchase_ip,
            }.items()
            if v is not None
        }
        if not isinstance(custom_name, NotGiven):
            body["custom_name"] = custom_name
        if not isinstance(folder_id, NotGiven):
            body["folder_id"] = folder_id
        if not isinstance(max_downloads, NotGiven):
            body["max_downloads"] = max_downloads
        _validate_model(
            body,
            {
                "name": "SdkReplaceVariantDeliverableFileSettingsRequestApplicationJson",
                "required": [],
                "properties": {
                    "custom_name": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "string"},
                    },
                    "folder_id": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "watermark": {"kind": "primitive", "type": "boolean"},
                    "max_downloads": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "limit_to_purchase_ip": {"kind": "primitive", "type": "boolean"},
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return await self._client.request(
            method="put",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            body=body,
            model=SdkReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJson,
            request_options=request_options,
        )

    async def update(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        custom_name: str | None | NotGiven = NOT_GIVEN,
        folder_id: int | None | NotGiven = NOT_GIVEN,
        watermark: bool | None = None,
        max_downloads: int | None | NotGiven = NOT_GIVEN,
        limit_to_purchase_ip: bool | None = None,
        request_options: RequestOptions | None = None,
    ) -> SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson:
        """Update a variant deliverable file

        Update a variant deliverable file. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            custom_name: The custom name.
            folder_id: The folder id.
            watermark: The watermark.
            max_downloads: The max downloads.
            limit_to_purchase_ip: The limit to purchase ip.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "updateVariantDeliverableFile",
        }
        body: dict[str, Any] = {
            k: v
            for k, v in {
                "watermark": watermark,
                "limit_to_purchase_ip": limit_to_purchase_ip,
            }.items()
            if v is not None
        }
        if not isinstance(custom_name, NotGiven):
            body["custom_name"] = custom_name
        if not isinstance(folder_id, NotGiven):
            body["folder_id"] = folder_id
        if not isinstance(max_downloads, NotGiven):
            body["max_downloads"] = max_downloads
        _validate_model(
            body,
            {
                "name": "SdkUpdateVariantDeliverableFileRequestApplicationJson",
                "required": [],
                "properties": {
                    "custom_name": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "string"},
                    },
                    "folder_id": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "watermark": {"kind": "primitive", "type": "boolean"},
                    "max_downloads": {
                        "kind": "nullable",
                        "inner": {
                            "kind": "primitive",
                            "type": "integer",
                            "constraints": {"minimum": 1},
                        },
                    },
                    "limit_to_purchase_ip": {"kind": "primitive", "type": "boolean"},
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return await self._client.request(
            method="patch",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            body=body,
            model=SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson,
            request_options=request_options,
        )

    async def delete(
        self,
        product: str,
        variant: int,
        file: int,
        *,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Delete a variant deliverable file

        Delete a variant deliverable file. Requires the listing Sanctum ability. The file is scoped through the authenticated store, product, and variant. Internal storage keys are immutable and never returned. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            product: The product identifier or slug. The product must belong to the authenticated store.
            variant: The product variant identifier.
            file: The managed deliverable file identifier.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "deleteVariantDeliverableFile",
        }
        await self._client.request(
            method="delete",
            path=(
                "v2",
                "products",
                str(product),
                "variants",
                str(variant),
                "deliverable",
                "files",
                str(file),
            ),
            request_options=request_options,
        )
