# This file is auto-generated by oagen. Do not edit.

import json

import pytest

from sellapp_sdk import AsyncSellAppClient, SellAppClient
from sellapp_sdk._errors import (
    AuthenticationError,
    BadRequestError,
    NotFoundError,
    RateLimitExceededError,
    ServerError,
    UnprocessableEntityError,
)
from sellapp_sdk._pagination import AsyncPage, SyncPage
from sellapp_sdk.common.models import (
    SdkQueueVariantSerialImportRequestMultipartFormDataParsingMode,
)
from sellapp_sdk.variant_serials.models import (
    ListVariantSerialInventoryResponseValue200ApplicationJsonPropertyDataItem,
    SdkAppendVariantSerialInventoryResponseValue201ApplicationJson,
    SdkQueueVariantSerialImportResponseValue202ApplicationJson,
    SdkReplaceVariantSerialInventoryResponseValue200ApplicationJson,
)
from tests.generated_helpers import load_fixture


class TestVariantSerials:
    def test_list(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "list_list_variant_serial_inventory_response_value_200_application_json_property_data_item.json"
            ),
        )
        page = sellapp_sdk.variant_serials.list("test_product", "test_variant")
        assert isinstance(page, SyncPage)
        assert len(page.data) == 1
        assert isinstance(
            page.data[0],
            ListVariantSerialInventoryResponseValue200ApplicationJsonPropertyDataItem,
        )

    def test_list_empty_page(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = sellapp_sdk.variant_serials.list("test_product", "test_variant")
        assert isinstance(page, SyncPage)
        assert page.data == []

    def test_list_encodes_query_params(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        sellapp_sdk.variant_serials.list(
            "test_product",
            "test_variant",
            limit=10,
            before="cursor before",
            after="cursor/after",
            search="value search/test",
            page=7,
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["search"] == "value search/test"
        assert request.url.params["page"] == "7"

    def test_append(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_append_variant_serial_inventory_response_value_201_application_json.json"
            ),
        )
        result = sellapp_sdk.variant_serials.append(
            "test_product", "test_variant", serials=["test_serials_0"]
        )
        assert isinstance(
            result, SdkAppendVariantSerialInventoryResponseValue201ApplicationJson
        )
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials"
        )
        body = json.loads(request.content)
        assert "serials" in body

    def test_replace(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_replace_variant_serial_inventory_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.variant_serials.replace(
            "test_product", "test_variant", serials=["test_serials_0"]
        )
        assert isinstance(
            result, SdkReplaceVariantSerialInventoryResponseValue200ApplicationJson
        )
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials"
        )
        body = json.loads(request.content)
        assert "serials" in body

    def test_queue(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_queue_variant_serial_import_response_value_202_application_json.json"
            ),
        )
        result = sellapp_sdk.variant_serials.queue(
            "test_product",
            "test_variant",
            file="test_file",
            parsing_mode=SdkQueueVariantSerialImportRequestMultipartFormDataParsingMode(
                "COMMA"
            ),
        )
        assert isinstance(
            result, SdkQueueVariantSerialImportResponseValue202ApplicationJson
        )
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials/import"
        )
        wire_body = request.content.decode("utf-8", errors="replace")
        assert "file" in wire_body
        assert "parsing_mode" in wire_body

    def test_delete(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(status_code=200, content=b"")
        result = sellapp_sdk.variant_serials.delete(
            "test_product", "test_variant", "test_serial"
        )
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials/test_serial"
        )

    def test_list_with_request_options(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        sellapp_sdk.variant_serials.list(
            "test_product",
            "test_variant",
            request_options={"headers": {"X-Custom": "value"}},
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    def test_list_unauthorized(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Unauthorized"},
        )
        with pytest.raises(AuthenticationError):
            sellapp_sdk.variant_serials.list("test_product", "test_variant")

    def test_list_not_found(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            sellapp_sdk.close()

    def test_list_rate_limited(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            sellapp_sdk.close()

    def test_list_server_error(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            sellapp_sdk.close()

    def test_list_bad_request(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            sellapp_sdk.close()

    def test_list_unprocessable(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            sellapp_sdk.close()


class TestAsyncVariantSerials:
    @pytest.mark.asyncio
    async def test_list(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "list_list_variant_serial_inventory_response_value_200_application_json_property_data_item.json"
            )
        )
        page = await async_sellapp_sdk.variant_serials.list(
            "test_product", "test_variant"
        )
        assert isinstance(page, AsyncPage)
        assert len(page.data) == 1
        assert isinstance(
            page.data[0],
            ListVariantSerialInventoryResponseValue200ApplicationJsonPropertyDataItem,
        )

    @pytest.mark.asyncio
    async def test_list_empty_page(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = await async_sellapp_sdk.variant_serials.list(
            "test_product", "test_variant"
        )
        assert isinstance(page, AsyncPage)
        assert page.data == []

    @pytest.mark.asyncio
    async def test_list_encodes_query_params(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_sellapp_sdk.variant_serials.list(
            "test_product",
            "test_variant",
            limit=10,
            before="cursor before",
            after="cursor/after",
            search="value search/test",
            page=7,
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["search"] == "value search/test"
        assert request.url.params["page"] == "7"

    @pytest.mark.asyncio
    async def test_append(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_append_variant_serial_inventory_response_value_201_application_json.json"
            )
        )
        result = await async_sellapp_sdk.variant_serials.append(
            "test_product", "test_variant", serials=["test_serials_0"]
        )
        assert isinstance(
            result, SdkAppendVariantSerialInventoryResponseValue201ApplicationJson
        )
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials"
        )

    @pytest.mark.asyncio
    async def test_replace(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_replace_variant_serial_inventory_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.variant_serials.replace(
            "test_product", "test_variant", serials=["test_serials_0"]
        )
        assert isinstance(
            result, SdkReplaceVariantSerialInventoryResponseValue200ApplicationJson
        )
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials"
        )

    @pytest.mark.asyncio
    async def test_queue(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_queue_variant_serial_import_response_value_202_application_json.json"
            )
        )
        result = await async_sellapp_sdk.variant_serials.queue(
            "test_product",
            "test_variant",
            file="test_file",
            parsing_mode=SdkQueueVariantSerialImportRequestMultipartFormDataParsingMode(
                "COMMA"
            ),
        )
        assert isinstance(
            result, SdkQueueVariantSerialImportResponseValue202ApplicationJson
        )
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials/import"
        )

    @pytest.mark.asyncio
    async def test_delete(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(status_code=200, content=b"")
        result = await async_sellapp_sdk.variant_serials.delete(
            "test_product", "test_variant", "test_serial"
        )
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith(
            "/v2/products/test_product/variants/test_variant/serials/test_serial"
        )

    @pytest.mark.asyncio
    async def test_list_with_request_options(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_sellapp_sdk.variant_serials.list(
            "test_product",
            "test_variant",
            request_options={"headers": {"X-Custom": "value"}},
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    @pytest.mark.asyncio
    async def test_list_unauthorized(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(status_code=401, json={"message": "Unauthorized"})
        with pytest.raises(AuthenticationError):
            await async_sellapp_sdk.variant_serials.list("test_product", "test_variant")

    @pytest.mark.asyncio
    async def test_list_not_found(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                await sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_rate_limited(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                await sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_server_error(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                await sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_bad_request(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                await sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_unprocessable(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                await sellapp_sdk.variant_serials.list("test_product", "test_variant")
        finally:
            await sellapp_sdk.close()
