# This file is auto-generated by oagen. Do not edit.

"""Model round-trip tests: from_dict(to_dict()) preserves data."""

from sellapp_sdk.add_ons.models import (
    CreateAddOnDraftRequestApplicationJsonPropertyVariant,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyBulkDiscountItem,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverable,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingPropertyAvailabilityItem,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyOtherSettings,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricing,
    CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricingPropertyPrice,
    CreateAddOnDraftResponseValue201ApplicationJsonPropertyData,
    CreateAddOnDraftResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem,
    DeleteAddOnResponseValue200ApplicationJsonPropertyData,
    DeleteAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem,
    GetAddOnResponseValue200ApplicationJsonPropertyData,
    GetAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem,
    ReplaceAddOnResponseValue200ApplicationJsonPropertyData,
    ReplaceAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem,
    ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyData,
    ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem,
    ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem,
    ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem,
    SdkCreateAddOnDraftResponseValue201ApplicationJson,
    SdkDeleteAddOnResponseValue200ApplicationJson,
    SdkGetAddOnResponseValue200ApplicationJson,
    SdkReplaceAddOnResponseValue200ApplicationJson,
    SdkReplaceAddOnSParentProductsResponseValue200ApplicationJson,
    SdkReplaceProductSAddOnsResponseValue200ApplicationJson,
    SdkUpdateAddOnResponseValue200ApplicationJson,
    SearchAddOnsRequestApplicationJsonPropertyFiltersItem,
    SearchAddOnsRequestApplicationJsonPropertyIncludesItem,
    SearchAddOnsRequestApplicationJsonPropertySearch,
    SearchAddOnsRequestApplicationJsonPropertySortItem,
    UpdateAddOnResponseValue200ApplicationJsonPropertyData,
    UpdateAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem,
)
from tests.generated_helpers import load_fixture


class TestModelRoundTrip:
    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_property_availability_item_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_property_availability_item.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingPropertyAvailabilityItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_property_availability_item_minimal_payload(
        self,
    ):
        data = {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBookingPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["day"] == data["day"]
        assert serialized["enabled"] == data["enabled"]
        assert serialized["start"] == data["start"]
        assert serialized["end"] == data["end"]

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_minimal_payload(
        self,
    ):
        data = {}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {"video_provider_connection_id": 1}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert "mode" not in serialized
        assert "conflict_scope" not in serialized
        assert "timezone" not in serialized
        assert "duration_minutes" not in serialized
        assert "capacity_per_slot" not in serialized
        assert "min_notice_minutes" not in serialized
        assert "max_advance_days" not in serialized
        assert "buffer_before_minutes" not in serialized
        assert "buffer_after_minutes" not in serialized
        assert "availability" not in serialized
        assert "provider_connection_ids" not in serialized
        assert "video_provider" not in serialized
        assert "reminders_enabled" not in serialized
        assert "reminder_offset_value" not in serialized
        assert "reminder_offset_unit" not in serialized
        assert "meta" not in serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_preserves_nullable_fields(
        self,
    ):
        data = {
            "mode": "native",
            "conflict_scope": "product",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": None,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["video_provider_connection_id"] is None

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "mode": "native",
            "conflict_scope": "unexpected_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_booking_conflict_scope",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": 1,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_credit_rate_tiers_item_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_credit_rate_tiers_item.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_credit_rate_tiers_item_minimal_payload(
        self,
    ):
        data = {"min_quantity": 1, "max_quantity": None, "unit_price": "0.75"}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["min_quantity"] == data["min_quantity"]
        assert serialized["max_quantity"] == data["max_quantity"]
        assert serialized["unit_price"] == data["unit_price"]

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_property_credit_rate_tiers_item_preserves_nullable_fields(
        self,
    ):
        data = {"min_quantity": 1, "max_quantity": None, "unit_price": "0.75"}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["max_quantity"] is None

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_minimal_payload(
        self,
    ):
        data = {}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {"stock": 1}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert "serials" not in serialized
        assert "removeDuplicate" not in serialized
        assert "parsingMode" not in serialized
        assert "comment" not in serialized
        assert "webhook" not in serialized
        assert "booking" not in serialized
        assert "credit_rate_tiers" not in serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "stock": None,
            "serials": ["test_serials"],
            "removeDuplicate": True,
            "parsingMode": "COMMA",
            "comment": "test_comment",
            "webhook": "test_webhook",
            "booking": {
                "mode": "native",
                "conflict_scope": "product",
                "timezone": "America/New_York",
                "duration_minutes": 30,
                "capacity_per_slot": 1,
                "min_notice_minutes": 1,
                "max_advance_days": 1,
                "buffer_before_minutes": 30,
                "buffer_after_minutes": 30,
                "availability": [
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                ],
                "provider_connection_ids": [1],
                "video_provider": "none",
                "video_provider_connection_id": 1,
                "reminders_enabled": True,
                "reminder_offset_value": 1,
                "reminder_offset_unit": "minutes",
                "meta": {},
            },
            "credit_rate_tiers": [
                {"min_quantity": 1, "max_quantity": 1, "unit_price": "0.75"}
            ],
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["stock"] is None

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "stock": 1,
            "serials": ["test_serials"],
            "removeDuplicate": True,
            "parsingMode": "unexpected_create_add_on_draft_request_application_json_property_variant_property_deliverable_property_data_parsing_mode",
            "comment": "test_comment",
            "webhook": "test_webhook",
            "booking": {
                "mode": "native",
                "conflict_scope": "product",
                "timezone": "America/New_York",
                "duration_minutes": 30,
                "capacity_per_slot": 1,
                "min_notice_minutes": 1,
                "max_advance_days": 1,
                "buffer_before_minutes": 30,
                "buffer_after_minutes": 30,
                "availability": [
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                ],
                "provider_connection_ids": [1],
                "video_provider": "none",
                "video_provider_connection_id": 1,
                "reminders_enabled": True,
                "reminder_offset_value": 1,
                "reminder_offset_unit": "minutes",
                "meta": {},
            },
            "credit_rate_tiers": [
                {"min_quantity": 1, "max_quantity": 1, "unit_price": "0.75"}
            ],
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_deliverable.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverable.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverable.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_deliverable_minimal_payload(
        self,
    ):
        data = {
            "types": [
                "DOWNLOADABLE",
                "TEXT",
                "DYNAMIC",
                "MANUAL",
                "LICENSE_KEY",
                "BUNDLE",
                "BOOKING",
                "CREDITS",
            ],
            "data": {
                "stock": 1,
                "serials": ["test_serials"],
                "removeDuplicate": True,
                "parsingMode": "COMMA",
                "comment": "test_comment",
                "webhook": "test_webhook",
                "booking": {
                    "mode": "native",
                    "conflict_scope": "product",
                    "timezone": "America/New_York",
                    "duration_minutes": 30,
                    "capacity_per_slot": 1,
                    "min_notice_minutes": 1,
                    "max_advance_days": 1,
                    "buffer_before_minutes": 30,
                    "buffer_after_minutes": 30,
                    "availability": [
                        {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                        {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                        {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                        {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                        {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                        {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                        {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    ],
                    "provider_connection_ids": [1],
                    "video_provider": "none",
                    "video_provider_connection_id": 1,
                    "reminders_enabled": True,
                    "reminder_offset_value": 1,
                    "reminder_offset_unit": "minutes",
                    "meta": {},
                },
                "credit_rate_tiers": [
                    {"min_quantity": 1, "max_quantity": 1, "unit_price": "0.75"}
                ],
            },
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverable.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["types"] == data["types"]
        assert serialized["data"] == data["data"]

    def test_create_add_on_draft_request_application_json_property_variant_property_pricing_property_price_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_pricing_property_price.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricingPropertyPrice.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricingPropertyPrice.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_pricing_property_price_minimal_payload(
        self,
    ):
        data = {"price": 1, "currency": "test_currency"}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricingPropertyPrice.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["price"] == data["price"]
        assert serialized["currency"] == data["currency"]

    def test_create_add_on_draft_request_application_json_property_variant_property_pricing_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_pricing.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricing.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricing.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_pricing_minimal_payload(
        self,
    ):
        data = {"humble": True, "price": {"price": 1, "currency": "test_currency"}}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricing.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["humble"] == data["humble"]
        assert serialized["price"] == data["price"]

    def test_create_add_on_draft_request_application_json_property_variant_property_bulk_discount_item_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_bulk_discount_item.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyBulkDiscountItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyBulkDiscountItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_bulk_discount_item_minimal_payload(
        self,
    ):
        data = {"minimum_purchase_amount": 1, "discount_percentage": 1}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyBulkDiscountItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["minimum_purchase_amount"] == data["minimum_purchase_amount"]
        assert serialized["discount_percentage"] == data["discount_percentage"]

    def test_create_add_on_draft_request_application_json_property_variant_property_other_settings_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant_property_other_settings.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyOtherSettings.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyOtherSettings.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_property_other_settings_minimal_payload(
        self,
    ):
        data = {}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyOtherSettings.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_create_add_on_draft_request_application_json_property_variant_property_other_settings_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {}
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyOtherSettings.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert "quantity_increments" not in serialized

    def test_create_add_on_draft_request_application_json_property_variant_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_request_application_json_property_variant.json"
        )
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariant.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftRequestApplicationJsonPropertyVariant.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_request_application_json_property_variant_minimal_payload(
        self,
    ):
        data = {
            "title": "test_title",
            "description": "test_description",
            "deliverable": {
                "types": [
                    "DOWNLOADABLE",
                    "TEXT",
                    "DYNAMIC",
                    "MANUAL",
                    "LICENSE_KEY",
                    "BUNDLE",
                    "BOOKING",
                    "CREDITS",
                ],
                "data": {
                    "stock": 1,
                    "serials": ["test_serials"],
                    "removeDuplicate": True,
                    "parsingMode": "COMMA",
                    "comment": "test_comment",
                    "webhook": "test_webhook",
                    "booking": {
                        "mode": "native",
                        "conflict_scope": "product",
                        "timezone": "America/New_York",
                        "duration_minutes": 30,
                        "capacity_per_slot": 1,
                        "min_notice_minutes": 1,
                        "max_advance_days": 1,
                        "buffer_before_minutes": 30,
                        "buffer_after_minutes": 30,
                        "availability": [
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                        ],
                        "provider_connection_ids": [1],
                        "video_provider": "none",
                        "video_provider_connection_id": 1,
                        "reminders_enabled": True,
                        "reminder_offset_value": 1,
                        "reminder_offset_unit": "minutes",
                        "meta": {},
                    },
                    "credit_rate_tiers": [
                        {"min_quantity": 1, "max_quantity": 1, "unit_price": "0.75"}
                    ],
                },
            },
            "pricing": {
                "humble": True,
                "price": {"price": 1, "currency": "test_currency"},
            },
            "payment_methods": [
                "AUTHNET",
                "BTCPAY",
                "CASHAPP",
                "COINBASE",
                "PADDLE",
                "PAYDASH",
                "PAYPAL",
                "PAYSTACK",
                "SQUARE",
                "STRIPE",
                "VENMO",
                "NMI",
                "MERCADO_PAGO",
                "MOLLIE",
                "RAZORPAY",
                "CUSTOM_PAYMENT_METHOD",
                "LIFI",
                "BTC",
                "LTC",
                "ETH",
                "XMR",
                "SOL",
                "ADA",
                "BNB",
                "TRX",
                "MATIC",
                "ETH_USDT",
                "ETH_USDC",
                "ETH_UNI",
                "ETH_SHIB",
                "ETH_DAI",
                "BNB_USDT",
                "BNB_USDC",
                "TRX_USDT",
                "TRX_USDC",
                "SOL_USDT",
                "SOL_USDC",
            ],
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariant.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["title"] == data["title"]
        assert serialized["description"] == data["description"]
        assert serialized["deliverable"] == data["deliverable"]
        assert serialized["pricing"] == data["pricing"]
        assert serialized["payment_methods"] == data["payment_methods"]

    def test_create_add_on_draft_request_application_json_property_variant_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {
            "title": "test_title",
            "description": "test_description",
            "deliverable": {
                "types": [
                    "DOWNLOADABLE",
                    "TEXT",
                    "DYNAMIC",
                    "MANUAL",
                    "LICENSE_KEY",
                    "BUNDLE",
                    "BOOKING",
                    "CREDITS",
                ],
                "data": {
                    "stock": 1,
                    "serials": ["test_serials"],
                    "removeDuplicate": True,
                    "parsingMode": "COMMA",
                    "comment": "test_comment",
                    "webhook": "test_webhook",
                    "booking": {
                        "mode": "native",
                        "conflict_scope": "product",
                        "timezone": "America/New_York",
                        "duration_minutes": 30,
                        "capacity_per_slot": 1,
                        "min_notice_minutes": 1,
                        "max_advance_days": 1,
                        "buffer_before_minutes": 30,
                        "buffer_after_minutes": 30,
                        "availability": [
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                        ],
                        "provider_connection_ids": [1],
                        "video_provider": "none",
                        "video_provider_connection_id": 1,
                        "reminders_enabled": True,
                        "reminder_offset_value": 1,
                        "reminder_offset_unit": "minutes",
                        "meta": {},
                    },
                    "credit_rate_tiers": [
                        {"min_quantity": 1, "max_quantity": 1, "unit_price": "0.75"}
                    ],
                },
            },
            "pricing": {
                "humble": True,
                "price": {"price": 1, "currency": "test_currency"},
            },
            "maximum_purchase_quantity": 1,
            "payment_methods": [
                "AUTHNET",
                "BTCPAY",
                "CASHAPP",
                "COINBASE",
                "PADDLE",
                "PAYDASH",
                "PAYPAL",
                "PAYSTACK",
                "SQUARE",
                "STRIPE",
                "VENMO",
                "NMI",
                "MERCADO_PAGO",
                "MOLLIE",
                "RAZORPAY",
                "CUSTOM_PAYMENT_METHOD",
                "LIFI",
                "BTC",
                "LTC",
                "ETH",
                "XMR",
                "SOL",
                "ADA",
                "BNB",
                "TRX",
                "MATIC",
                "ETH_USDT",
                "ETH_USDC",
                "ETH_UNI",
                "ETH_SHIB",
                "ETH_DAI",
                "BNB_USDT",
                "BNB_USDC",
                "TRX_USDT",
                "TRX_USDC",
                "SOL_USDT",
                "SOL_USDC",
            ],
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariant.from_dict(data)
        serialized = instance.to_dict()
        assert "minimum_purchase_quantity" not in serialized
        assert "bulk_discount" not in serialized
        assert "other_settings" not in serialized
        assert "expected_updated_at" not in serialized

    def test_create_add_on_draft_request_application_json_property_variant_preserves_nullable_fields(
        self,
    ):
        data = {
            "title": "test_title",
            "description": "test_description",
            "deliverable": {
                "types": [
                    "DOWNLOADABLE",
                    "TEXT",
                    "DYNAMIC",
                    "MANUAL",
                    "LICENSE_KEY",
                    "BUNDLE",
                    "BOOKING",
                    "CREDITS",
                ],
                "data": {
                    "stock": 1,
                    "serials": ["test_serials"],
                    "removeDuplicate": True,
                    "parsingMode": "COMMA",
                    "comment": "test_comment",
                    "webhook": "test_webhook",
                    "booking": {
                        "mode": "native",
                        "conflict_scope": "product",
                        "timezone": "America/New_York",
                        "duration_minutes": 30,
                        "capacity_per_slot": 1,
                        "min_notice_minutes": 1,
                        "max_advance_days": 1,
                        "buffer_before_minutes": 30,
                        "buffer_after_minutes": 30,
                        "availability": [
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                            {
                                "day": 1,
                                "enabled": True,
                                "start": "09:00",
                                "end": "17:00",
                            },
                        ],
                        "provider_connection_ids": [1],
                        "video_provider": "none",
                        "video_provider_connection_id": 1,
                        "reminders_enabled": True,
                        "reminder_offset_value": 1,
                        "reminder_offset_unit": "minutes",
                        "meta": {},
                    },
                    "credit_rate_tiers": [
                        {"min_quantity": 1, "max_quantity": 1, "unit_price": "0.75"}
                    ],
                },
            },
            "pricing": {
                "humble": True,
                "price": {"price": 1, "currency": "test_currency"},
            },
            "minimum_purchase_quantity": 1,
            "maximum_purchase_quantity": None,
            "bulk_discount": [{"minimum_purchase_amount": 1, "discount_percentage": 1}],
            "payment_methods": [
                "AUTHNET",
                "BTCPAY",
                "CASHAPP",
                "COINBASE",
                "PADDLE",
                "PAYDASH",
                "PAYPAL",
                "PAYSTACK",
                "SQUARE",
                "STRIPE",
                "VENMO",
                "NMI",
                "MERCADO_PAGO",
                "MOLLIE",
                "RAZORPAY",
                "CUSTOM_PAYMENT_METHOD",
                "LIFI",
                "BTC",
                "LTC",
                "ETH",
                "XMR",
                "SOL",
                "ADA",
                "BNB",
                "TRX",
                "MATIC",
                "ETH_USDT",
                "ETH_USDC",
                "ETH_UNI",
                "ETH_SHIB",
                "ETH_DAI",
                "BNB_USDT",
                "BNB_USDC",
                "TRX_USDT",
                "TRX_USDC",
                "SOL_USDT",
                "SOL_USDC",
            ],
            "other_settings": {"quantity_increments": 1},
            "expected_updated_at": "2023-01-01T00:00:00.000Z",
        }
        instance = CreateAddOnDraftRequestApplicationJsonPropertyVariant.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["maximum_purchase_quantity"] is None

    def test_create_add_on_draft_response_value_201_application_json_property_data_property_variants_item_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_response_value_201_application_json_property_data_property_variants_item.json"
        )
        instance = CreateAddOnDraftResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CreateAddOnDraftResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_response_value_201_application_json_property_data_property_variants_item_minimal_payload(
        self,
    ):
        data = {"id": 8801, "title": "Default", "is_draft": False}
        instance = CreateAddOnDraftResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["title"] == data["title"]
        assert serialized["is_draft"] == data["is_draft"]

    def test_create_add_on_draft_response_value_201_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "create_add_on_draft_response_value_201_application_json_property_data.json"
        )
        instance = (
            CreateAddOnDraftResponseValue201ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            CreateAddOnDraftResponseValue201ApplicationJsonPropertyData.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_create_add_on_draft_response_value_201_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = (
            CreateAddOnDraftResponseValue201ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["store_id"] == data["store_id"]
        assert serialized["title"] == data["title"]
        assert serialized["slug"] == data["slug"]
        assert serialized["description"] == data["description"]
        assert serialized["visibility"] == data["visibility"]
        assert serialized["type"] == data["type"]
        assert serialized["is_draft"] == data["is_draft"]
        assert serialized["is_discoverable"] == data["is_discoverable"]
        assert serialized["parent_product_ids"] == data["parent_product_ids"]
        assert serialized["variants"] == data["variants"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["deleted_at"] == data["deleted_at"]

    def test_create_add_on_draft_response_value_201_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = (
            CreateAddOnDraftResponseValue201ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["deleted_at"] is None

    def test_create_add_on_draft_response_value_201_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "unexpected_create_add_on_draft_response_value_201_application_json_property_data_visibility",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": "2023-01-01T00:00:00.000Z",
        }
        instance = (
            CreateAddOnDraftResponseValue201ApplicationJsonPropertyData.from_dict(data)
        )
        assert instance.to_dict() == data

    def test_sdk_create_add_on_draft_response_value_201_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_create_add_on_draft_response_value_201_application_json.json"
        )
        instance = SdkCreateAddOnDraftResponseValue201ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkCreateAddOnDraftResponseValue201ApplicationJson.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_sdk_create_add_on_draft_response_value_201_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": 410,
                "store_id": 12,
                "title": "Customer support",
                "slug": "customer-support",
                "description": "Priority support for launches scheduled suspiciously close to Friday.",
                "visibility": "PUBLIC",
                "type": "addon",
                "is_draft": True,
                "is_discoverable": False,
                "parent_product_ids": [120, 121],
                "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "deleted_at": "2023-01-01T00:00:00.000Z",
            }
        }
        instance = SdkCreateAddOnDraftResponseValue201ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_search_add_ons_request_application_json_property_filters_item_round_trip(
        self,
    ):
        data = load_fixture(
            "search_add_ons_request_application_json_property_filters_item.json"
        )
        instance = SearchAddOnsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SearchAddOnsRequestApplicationJsonPropertyFiltersItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_search_add_ons_request_application_json_property_filters_item_minimal_payload(
        self,
    ):
        data = {}
        instance = SearchAddOnsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        assert instance.to_dict() is not None

    def test_search_add_ons_request_application_json_property_filters_item_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {}
        instance = SearchAddOnsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        serialized = instance.to_dict()
        assert "field" not in serialized
        assert "operator" not in serialized
        assert "value" not in serialized
        assert "type" not in serialized
        assert "nested" not in serialized

    def test_search_add_ons_request_application_json_property_filters_item_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "field": "test_field",
            "operator": "test_operator",
            "value": {},
            "type": "unexpected_search_add_ons_request_application_json_property_filters_item_type",
            "nested": [{}],
        }
        instance = SearchAddOnsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        assert instance.to_dict() == data

    def test_search_add_ons_request_application_json_property_sort_item_round_trip(
        self,
    ):
        data = load_fixture(
            "search_add_ons_request_application_json_property_sort_item.json"
        )
        instance = SearchAddOnsRequestApplicationJsonPropertySortItem.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SearchAddOnsRequestApplicationJsonPropertySortItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_search_add_ons_request_application_json_property_sort_item_minimal_payload(
        self,
    ):
        data = {"field": "test_field"}
        instance = SearchAddOnsRequestApplicationJsonPropertySortItem.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["field"] == data["field"]

    def test_search_add_ons_request_application_json_property_sort_item_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {"field": "test_field"}
        instance = SearchAddOnsRequestApplicationJsonPropertySortItem.from_dict(data)
        serialized = instance.to_dict()
        assert "direction" not in serialized

    def test_search_add_ons_request_application_json_property_sort_item_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "field": "test_field",
            "direction": "unexpected_search_add_ons_request_application_json_property_sort_item_direction",
        }
        instance = SearchAddOnsRequestApplicationJsonPropertySortItem.from_dict(data)
        assert instance.to_dict() == data

    def test_search_add_ons_request_application_json_property_search_round_trip(self):
        data = load_fixture(
            "search_add_ons_request_application_json_property_search.json"
        )
        instance = SearchAddOnsRequestApplicationJsonPropertySearch.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SearchAddOnsRequestApplicationJsonPropertySearch.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_search_add_ons_request_application_json_property_search_minimal_payload(
        self,
    ):
        data = {}
        instance = SearchAddOnsRequestApplicationJsonPropertySearch.from_dict(data)
        assert instance.to_dict() is not None

    def test_search_add_ons_request_application_json_property_search_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {"value": "test_value"}
        instance = SearchAddOnsRequestApplicationJsonPropertySearch.from_dict(data)
        serialized = instance.to_dict()
        assert "case_sensitive" not in serialized

    def test_search_add_ons_request_application_json_property_search_preserves_nullable_fields(
        self,
    ):
        data = {"value": None, "case_sensitive": True}
        instance = SearchAddOnsRequestApplicationJsonPropertySearch.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["value"] is None

    def test_search_add_ons_request_application_json_property_includes_item_round_trip(
        self,
    ):
        data = load_fixture(
            "search_add_ons_request_application_json_property_includes_item.json"
        )
        instance = SearchAddOnsRequestApplicationJsonPropertyIncludesItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = SearchAddOnsRequestApplicationJsonPropertyIncludesItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_search_add_ons_request_application_json_property_includes_item_minimal_payload(
        self,
    ):
        data = {"relation": "test_relation"}
        instance = SearchAddOnsRequestApplicationJsonPropertyIncludesItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["relation"] == data["relation"]

    def test_get_add_on_response_value_200_application_json_property_data_property_variants_item_round_trip(
        self,
    ):
        data = load_fixture(
            "get_add_on_response_value_200_application_json_property_data_property_variants_item.json"
        )
        instance = GetAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = GetAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_get_add_on_response_value_200_application_json_property_data_property_variants_item_minimal_payload(
        self,
    ):
        data = {"id": 8801, "title": "Default", "is_draft": False}
        instance = GetAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["title"] == data["title"]
        assert serialized["is_draft"] == data["is_draft"]

    def test_get_add_on_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "get_add_on_response_value_200_application_json_property_data.json"
        )
        instance = GetAddOnResponseValue200ApplicationJsonPropertyData.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = GetAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_get_add_on_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = GetAddOnResponseValue200ApplicationJsonPropertyData.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["store_id"] == data["store_id"]
        assert serialized["title"] == data["title"]
        assert serialized["slug"] == data["slug"]
        assert serialized["description"] == data["description"]
        assert serialized["visibility"] == data["visibility"]
        assert serialized["type"] == data["type"]
        assert serialized["is_draft"] == data["is_draft"]
        assert serialized["is_discoverable"] == data["is_discoverable"]
        assert serialized["parent_product_ids"] == data["parent_product_ids"]
        assert serialized["variants"] == data["variants"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["deleted_at"] == data["deleted_at"]

    def test_get_add_on_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = GetAddOnResponseValue200ApplicationJsonPropertyData.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["deleted_at"] is None

    def test_get_add_on_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "unexpected_get_add_on_response_value_200_application_json_property_data_visibility",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": "2023-01-01T00:00:00.000Z",
        }
        instance = GetAddOnResponseValue200ApplicationJsonPropertyData.from_dict(data)
        assert instance.to_dict() == data

    def test_sdk_get_add_on_response_value_200_application_json_round_trip(self):
        data = load_fixture("sdk_get_add_on_response_value_200_application_json.json")
        instance = SdkGetAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkGetAddOnResponseValue200ApplicationJson.from_dict(serialized)
        assert restored.to_dict() == serialized

    def test_sdk_get_add_on_response_value_200_application_json_minimal_payload(self):
        data = {
            "data": {
                "id": 410,
                "store_id": 12,
                "title": "Customer support",
                "slug": "customer-support",
                "description": "Priority support for launches scheduled suspiciously close to Friday.",
                "visibility": "PUBLIC",
                "type": "addon",
                "is_draft": True,
                "is_discoverable": False,
                "parent_product_ids": [120, 121],
                "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "deleted_at": "2023-01-01T00:00:00.000Z",
            }
        }
        instance = SdkGetAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_replace_add_on_response_value_200_application_json_property_data_property_variants_item_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_add_on_response_value_200_application_json_property_data_property_variants_item.json"
        )
        instance = ReplaceAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_add_on_response_value_200_application_json_property_data_property_variants_item_minimal_payload(
        self,
    ):
        data = {"id": 8801, "title": "Default", "is_draft": False}
        instance = ReplaceAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["title"] == data["title"]
        assert serialized["is_draft"] == data["is_draft"]

    def test_replace_add_on_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_add_on_response_value_200_application_json_property_data.json"
        )
        instance = ReplaceAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_add_on_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = ReplaceAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["store_id"] == data["store_id"]
        assert serialized["title"] == data["title"]
        assert serialized["slug"] == data["slug"]
        assert serialized["description"] == data["description"]
        assert serialized["visibility"] == data["visibility"]
        assert serialized["type"] == data["type"]
        assert serialized["is_draft"] == data["is_draft"]
        assert serialized["is_discoverable"] == data["is_discoverable"]
        assert serialized["parent_product_ids"] == data["parent_product_ids"]
        assert serialized["variants"] == data["variants"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["deleted_at"] == data["deleted_at"]

    def test_replace_add_on_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = ReplaceAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["deleted_at"] is None

    def test_replace_add_on_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "unexpected_replace_add_on_response_value_200_application_json_property_data_visibility",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": "2023-01-01T00:00:00.000Z",
        }
        instance = ReplaceAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_replace_add_on_response_value_200_application_json_round_trip(self):
        data = load_fixture(
            "sdk_replace_add_on_response_value_200_application_json.json"
        )
        instance = SdkReplaceAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkReplaceAddOnResponseValue200ApplicationJson.from_dict(serialized)
        assert restored.to_dict() == serialized

    def test_sdk_replace_add_on_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": 410,
                "store_id": 12,
                "title": "Customer support",
                "slug": "customer-support",
                "description": "Priority support for launches scheduled suspiciously close to Friday.",
                "visibility": "PUBLIC",
                "type": "addon",
                "is_draft": True,
                "is_discoverable": False,
                "parent_product_ids": [120, 121],
                "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "deleted_at": "2023-01-01T00:00:00.000Z",
            }
        }
        instance = SdkReplaceAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_update_add_on_response_value_200_application_json_property_data_property_variants_item_round_trip(
        self,
    ):
        data = load_fixture(
            "update_add_on_response_value_200_application_json_property_data_property_variants_item.json"
        )
        instance = UpdateAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = UpdateAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_update_add_on_response_value_200_application_json_property_data_property_variants_item_minimal_payload(
        self,
    ):
        data = {"id": 8801, "title": "Default", "is_draft": False}
        instance = UpdateAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["title"] == data["title"]
        assert serialized["is_draft"] == data["is_draft"]

    def test_update_add_on_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "update_add_on_response_value_200_application_json_property_data.json"
        )
        instance = UpdateAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = UpdateAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_update_add_on_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = UpdateAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["store_id"] == data["store_id"]
        assert serialized["title"] == data["title"]
        assert serialized["slug"] == data["slug"]
        assert serialized["description"] == data["description"]
        assert serialized["visibility"] == data["visibility"]
        assert serialized["type"] == data["type"]
        assert serialized["is_draft"] == data["is_draft"]
        assert serialized["is_discoverable"] == data["is_discoverable"]
        assert serialized["parent_product_ids"] == data["parent_product_ids"]
        assert serialized["variants"] == data["variants"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["deleted_at"] == data["deleted_at"]

    def test_update_add_on_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = UpdateAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["deleted_at"] is None

    def test_update_add_on_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "unexpected_update_add_on_response_value_200_application_json_property_data_visibility",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": "2023-01-01T00:00:00.000Z",
        }
        instance = UpdateAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_update_add_on_response_value_200_application_json_round_trip(self):
        data = load_fixture(
            "sdk_update_add_on_response_value_200_application_json.json"
        )
        instance = SdkUpdateAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkUpdateAddOnResponseValue200ApplicationJson.from_dict(serialized)
        assert restored.to_dict() == serialized

    def test_sdk_update_add_on_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": 410,
                "store_id": 12,
                "title": "Customer support",
                "slug": "customer-support",
                "description": "Priority support for launches scheduled suspiciously close to Friday.",
                "visibility": "PUBLIC",
                "type": "addon",
                "is_draft": True,
                "is_discoverable": False,
                "parent_product_ids": [120, 121],
                "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "deleted_at": "2023-01-01T00:00:00.000Z",
            }
        }
        instance = SdkUpdateAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_delete_add_on_response_value_200_application_json_property_data_property_variants_item_round_trip(
        self,
    ):
        data = load_fixture(
            "delete_add_on_response_value_200_application_json_property_data_property_variants_item.json"
        )
        instance = DeleteAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = DeleteAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_delete_add_on_response_value_200_application_json_property_data_property_variants_item_minimal_payload(
        self,
    ):
        data = {"id": 8801, "title": "Default", "is_draft": False}
        instance = DeleteAddOnResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["title"] == data["title"]
        assert serialized["is_draft"] == data["is_draft"]

    def test_delete_add_on_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "delete_add_on_response_value_200_application_json_property_data.json"
        )
        instance = DeleteAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = DeleteAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_delete_add_on_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = DeleteAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["store_id"] == data["store_id"]
        assert serialized["title"] == data["title"]
        assert serialized["slug"] == data["slug"]
        assert serialized["description"] == data["description"]
        assert serialized["visibility"] == data["visibility"]
        assert serialized["type"] == data["type"]
        assert serialized["is_draft"] == data["is_draft"]
        assert serialized["is_discoverable"] == data["is_discoverable"]
        assert serialized["parent_product_ids"] == data["parent_product_ids"]
        assert serialized["variants"] == data["variants"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["deleted_at"] == data["deleted_at"]

    def test_delete_add_on_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = DeleteAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["deleted_at"] is None

    def test_delete_add_on_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "unexpected_delete_add_on_response_value_200_application_json_property_data_visibility",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": "2023-01-01T00:00:00.000Z",
        }
        instance = DeleteAddOnResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_delete_add_on_response_value_200_application_json_round_trip(self):
        data = load_fixture(
            "sdk_delete_add_on_response_value_200_application_json.json"
        )
        instance = SdkDeleteAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkDeleteAddOnResponseValue200ApplicationJson.from_dict(serialized)
        assert restored.to_dict() == serialized

    def test_sdk_delete_add_on_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": 410,
                "store_id": 12,
                "title": "Customer support",
                "slug": "customer-support",
                "description": "Priority support for launches scheduled suspiciously close to Friday.",
                "visibility": "PUBLIC",
                "type": "addon",
                "is_draft": True,
                "is_discoverable": False,
                "parent_product_ids": [120, 121],
                "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "deleted_at": "2023-01-01T00:00:00.000Z",
            }
        }
        instance = SdkDeleteAddOnResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_replace_add_on_s_parent_products_response_value_200_application_json_property_data_property_variants_item_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_add_on_s_parent_products_response_value_200_application_json_property_data_property_variants_item.json"
        )
        instance = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_add_on_s_parent_products_response_value_200_application_json_property_data_property_variants_item_minimal_payload(
        self,
    ):
        data = {"id": 8801, "title": "Default", "is_draft": False}
        instance = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["title"] == data["title"]
        assert serialized["is_draft"] == data["is_draft"]

    def test_replace_add_on_s_parent_products_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_add_on_s_parent_products_response_value_200_application_json_property_data.json"
        )
        instance = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_add_on_s_parent_products_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["store_id"] == data["store_id"]
        assert serialized["title"] == data["title"]
        assert serialized["slug"] == data["slug"]
        assert serialized["description"] == data["description"]
        assert serialized["visibility"] == data["visibility"]
        assert serialized["type"] == data["type"]
        assert serialized["is_draft"] == data["is_draft"]
        assert serialized["is_discoverable"] == data["is_discoverable"]
        assert serialized["parent_product_ids"] == data["parent_product_ids"]
        assert serialized["variants"] == data["variants"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["deleted_at"] == data["deleted_at"]

    def test_replace_add_on_s_parent_products_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["deleted_at"] is None

    def test_replace_add_on_s_parent_products_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "unexpected_replace_add_on_s_parent_products_response_value_200_application_json_property_data_visibility",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": "2023-01-01T00:00:00.000Z",
        }
        instance = ReplaceAddOnSParentProductsResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_replace_add_on_s_parent_products_response_value_200_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_replace_add_on_s_parent_products_response_value_200_application_json.json"
        )
        instance = (
            SdkReplaceAddOnSParentProductsResponseValue200ApplicationJson.from_dict(
                data
            )
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            SdkReplaceAddOnSParentProductsResponseValue200ApplicationJson.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_sdk_replace_add_on_s_parent_products_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": 410,
                "store_id": 12,
                "title": "Customer support",
                "slug": "customer-support",
                "description": "Priority support for launches scheduled suspiciously close to Friday.",
                "visibility": "PUBLIC",
                "type": "addon",
                "is_draft": True,
                "is_discoverable": False,
                "parent_product_ids": [120, 121],
                "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "deleted_at": "2023-01-01T00:00:00.000Z",
            }
        }
        instance = (
            SdkReplaceAddOnSParentProductsResponseValue200ApplicationJson.from_dict(
                data
            )
        )
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_replace_product_s_add_ons_response_value_200_application_json_property_data_item_property_variants_item_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_product_s_add_ons_response_value_200_application_json_property_data_item_property_variants_item.json"
        )
        instance = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_product_s_add_ons_response_value_200_application_json_property_data_item_property_variants_item_minimal_payload(
        self,
    ):
        data = {"id": 8801, "title": "Default", "is_draft": False}
        instance = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["title"] == data["title"]
        assert serialized["is_draft"] == data["is_draft"]

    def test_replace_product_s_add_ons_response_value_200_application_json_property_data_item_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_product_s_add_ons_response_value_200_application_json_property_data_item.json"
        )
        instance = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_product_s_add_ons_response_value_200_application_json_property_data_item_minimal_payload(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["store_id"] == data["store_id"]
        assert serialized["title"] == data["title"]
        assert serialized["slug"] == data["slug"]
        assert serialized["description"] == data["description"]
        assert serialized["visibility"] == data["visibility"]
        assert serialized["type"] == data["type"]
        assert serialized["is_draft"] == data["is_draft"]
        assert serialized["is_discoverable"] == data["is_discoverable"]
        assert serialized["parent_product_ids"] == data["parent_product_ids"]
        assert serialized["variants"] == data["variants"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["deleted_at"] == data["deleted_at"]

    def test_replace_product_s_add_ons_response_value_200_application_json_property_data_item_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "PUBLIC",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": None,
        }
        instance = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["deleted_at"] is None

    def test_replace_product_s_add_ons_response_value_200_application_json_property_data_item_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": 410,
            "store_id": 12,
            "title": "Customer support",
            "slug": "customer-support",
            "description": "Priority support for launches scheduled suspiciously close to Friday.",
            "visibility": "unexpected_replace_product_s_add_ons_response_value_200_application_json_property_data_item_visibility",
            "type": "addon",
            "is_draft": True,
            "is_discoverable": False,
            "parent_product_ids": [120, 121],
            "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "deleted_at": "2023-01-01T00:00:00.000Z",
        }
        instance = ReplaceProductSAddOnsResponseValue200ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_replace_product_s_add_ons_response_value_200_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_replace_product_s_add_ons_response_value_200_application_json.json"
        )
        instance = SdkReplaceProductSAddOnsResponseValue200ApplicationJson.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkReplaceProductSAddOnsResponseValue200ApplicationJson.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_sdk_replace_product_s_add_ons_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": [
                {
                    "id": 410,
                    "store_id": 12,
                    "title": "Customer support",
                    "slug": "customer-support",
                    "description": "Priority support for launches scheduled suspiciously close to Friday.",
                    "visibility": "PUBLIC",
                    "type": "addon",
                    "is_draft": True,
                    "is_discoverable": False,
                    "parent_product_ids": [120, 121],
                    "variants": [{"id": 8801, "title": "Default", "is_draft": False}],
                    "created_at": "2023-01-01T00:00:00.000Z",
                    "updated_at": "2023-01-01T00:00:00.000Z",
                    "deleted_at": "2023-01-01T00:00:00.000Z",
                }
            ]
        }
        instance = SdkReplaceProductSAddOnsResponseValue200ApplicationJson.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]
