# This file is auto-generated by oagen. Do not edit.

"""Model round-trip tests: from_dict(to_dict()) preserves data."""

from sellapp_sdk.bookings.models import (
    CancelAppointmentResponseValue200ApplicationJsonPropertyData,
    CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct,
    CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant,
    GetAppointmentResponseValue200ApplicationJsonPropertyData,
    GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct,
    GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant,
    GetBookingConfigurationResponseValue200ApplicationJsonPropertyData,
    GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem,
    ReplaceBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem,
    ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData,
    ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem,
    SdkCancelAppointmentResponseValue200ApplicationJson,
    SdkGetAppointmentResponseValue200ApplicationJson,
    SdkGetBookingConfigurationResponseValue200ApplicationJson,
    SdkReplaceBookingConfigurationResponseValue200ApplicationJson,
    SdkSetBookingDateAvailabilityResponseValue201ApplicationJson,
    SdkUpdateAppointmentResponseValue200ApplicationJson,
    SdkUpdateBookingConfigurationResponseValue200ApplicationJson,
    SearchAppointmentsRequestApplicationJsonPropertyFiltersItem,
    SearchAppointmentsRequestApplicationJsonPropertyIncludesItem,
    SearchAppointmentsRequestApplicationJsonPropertySearch,
    SearchAppointmentsRequestApplicationJsonPropertySortItem,
    SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItem,
    UpdateAppointmentResponseValue200ApplicationJsonPropertyData,
    UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct,
    UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant,
    UpdateBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem,
    UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyData,
    UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem,
)
from tests.generated_helpers import load_fixture


class TestModelRoundTrip:
    def test_search_appointments_request_application_json_property_filters_item_round_trip(
        self,
    ):
        data = load_fixture(
            "search_appointments_request_application_json_property_filters_item.json"
        )
        instance = (
            SearchAppointmentsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            SearchAppointmentsRequestApplicationJsonPropertyFiltersItem.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_search_appointments_request_application_json_property_filters_item_minimal_payload(
        self,
    ):
        data = {}
        instance = (
            SearchAppointmentsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        )
        assert instance.to_dict() is not None

    def test_search_appointments_request_application_json_property_filters_item_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {}
        instance = (
            SearchAppointmentsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        )
        serialized = instance.to_dict()
        assert "field" not in serialized
        assert "operator" not in serialized
        assert "value" not in serialized
        assert "type" not in serialized
        assert "nested" not in serialized

    def test_search_appointments_request_application_json_property_filters_item_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "field": "test_field",
            "operator": "test_operator",
            "value": {},
            "type": "unexpected_search_appointments_request_application_json_property_filters_item_type",
            "nested": [{}],
        }
        instance = (
            SearchAppointmentsRequestApplicationJsonPropertyFiltersItem.from_dict(data)
        )
        assert instance.to_dict() == data

    def test_search_appointments_request_application_json_property_sort_item_round_trip(
        self,
    ):
        data = load_fixture(
            "search_appointments_request_application_json_property_sort_item.json"
        )
        instance = SearchAppointmentsRequestApplicationJsonPropertySortItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = SearchAppointmentsRequestApplicationJsonPropertySortItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_search_appointments_request_application_json_property_sort_item_minimal_payload(
        self,
    ):
        data = {"field": "test_field"}
        instance = SearchAppointmentsRequestApplicationJsonPropertySortItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["field"] == data["field"]

    def test_search_appointments_request_application_json_property_sort_item_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {"field": "test_field"}
        instance = SearchAppointmentsRequestApplicationJsonPropertySortItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert "direction" not in serialized

    def test_search_appointments_request_application_json_property_sort_item_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "field": "test_field",
            "direction": "unexpected_search_appointments_request_application_json_property_sort_item_direction",
        }
        instance = SearchAppointmentsRequestApplicationJsonPropertySortItem.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_search_appointments_request_application_json_property_search_round_trip(
        self,
    ):
        data = load_fixture(
            "search_appointments_request_application_json_property_search.json"
        )
        instance = SearchAppointmentsRequestApplicationJsonPropertySearch.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = SearchAppointmentsRequestApplicationJsonPropertySearch.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_search_appointments_request_application_json_property_search_minimal_payload(
        self,
    ):
        data = {}
        instance = SearchAppointmentsRequestApplicationJsonPropertySearch.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_search_appointments_request_application_json_property_search_omits_absent_optional_non_nullable_fields(
        self,
    ):
        data = {"value": "test_value"}
        instance = SearchAppointmentsRequestApplicationJsonPropertySearch.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert "case_sensitive" not in serialized

    def test_search_appointments_request_application_json_property_search_preserves_nullable_fields(
        self,
    ):
        data = {"value": None, "case_sensitive": True}
        instance = SearchAppointmentsRequestApplicationJsonPropertySearch.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["value"] is None

    def test_search_appointments_request_application_json_property_includes_item_round_trip(
        self,
    ):
        data = load_fixture(
            "search_appointments_request_application_json_property_includes_item.json"
        )
        instance = (
            SearchAppointmentsRequestApplicationJsonPropertyIncludesItem.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            SearchAppointmentsRequestApplicationJsonPropertyIncludesItem.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_search_appointments_request_application_json_property_includes_item_minimal_payload(
        self,
    ):
        data = {"relation": "test_relation"}
        instance = (
            SearchAppointmentsRequestApplicationJsonPropertyIncludesItem.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["relation"] == data["relation"]

    def test_get_appointment_response_value_200_application_json_property_data_property_product_round_trip(
        self,
    ):
        data = load_fixture(
            "get_appointment_response_value_200_application_json_property_data_property_product.json"
        )
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_get_appointment_response_value_200_application_json_property_data_property_product_minimal_payload(
        self,
    ):
        data = {}
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_get_appointment_response_value_200_application_json_property_data_property_product_preserves_nullable_fields(
        self,
    ):
        data = {"id": None, "title": None}
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] is None
        assert serialized["title"] is None

    def test_get_appointment_response_value_200_application_json_property_data_property_variant_round_trip(
        self,
    ):
        data = load_fixture(
            "get_appointment_response_value_200_application_json_property_data_property_variant.json"
        )
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_get_appointment_response_value_200_application_json_property_data_property_variant_minimal_payload(
        self,
    ):
        data = {}
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_get_appointment_response_value_200_application_json_property_data_property_variant_preserves_nullable_fields(
        self,
    ):
        data = {"id": None, "title": None}
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] is None
        assert serialized["title"] is None

    def test_get_appointment_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "get_appointment_response_value_200_application_json_property_data.json"
        )
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = GetAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_get_appointment_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": None,
            "customer_email": None,
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "pending",
            "calendar_sync_status": "pending",
            "external_event_link": None,
            "video_join_url": None,
            "confirmed_at": None,
            "cancelled_at": None,
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": None,
            "variant": None,
        }
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["product_id"] == data["product_id"]
        assert serialized["product_variant_id"] == data["product_variant_id"]
        assert serialized["order_id"] == data["order_id"]
        assert serialized["invoice_id"] == data["invoice_id"]
        assert serialized["customer_id"] == data["customer_id"]
        assert serialized["customer_email"] == data["customer_email"]
        assert serialized["slot_start_at"] == data["slot_start_at"]
        assert serialized["slot_end_at"] == data["slot_end_at"]
        assert serialized["timezone"] == data["timezone"]
        assert serialized["quantity"] == data["quantity"]
        assert serialized["status"] == data["status"]
        assert serialized["calendar_sync_status"] == data["calendar_sync_status"]
        assert serialized["external_event_link"] == data["external_event_link"]
        assert serialized["video_join_url"] == data["video_join_url"]
        assert serialized["confirmed_at"] == data["confirmed_at"]
        assert serialized["cancelled_at"] == data["cancelled_at"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["product"] == data["product"]
        assert serialized["variant"] == data["variant"]

    def test_get_appointment_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": None,
            "customer_email": None,
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "pending",
            "calendar_sync_status": "pending",
            "external_event_link": None,
            "video_join_url": None,
            "confirmed_at": None,
            "cancelled_at": None,
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": None,
            "variant": None,
        }
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["customer_id"] is None
        assert serialized["customer_email"] is None
        assert serialized["external_event_link"] is None
        assert serialized["video_join_url"] is None
        assert serialized["confirmed_at"] is None
        assert serialized["cancelled_at"] is None
        assert serialized["product"] is None
        assert serialized["variant"] is None

    def test_get_appointment_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": 1,
            "customer_email": "test@example.com",
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "unexpected_get_appointment_response_value_200_application_json_property_data_status",
            "calendar_sync_status": "pending",
            "external_event_link": "test_external_event_link",
            "video_join_url": "video_join_url_01234",
            "confirmed_at": "2023-01-01T00:00:00.000Z",
            "cancelled_at": "2023-01-01T00:00:00.000Z",
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": {"id": 1, "title": "test_title"},
            "variant": {"id": 1, "title": "test_title"},
        }
        instance = GetAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_get_appointment_response_value_200_application_json_round_trip(self):
        data = load_fixture(
            "sdk_get_appointment_response_value_200_application_json.json"
        )
        instance = SdkGetAppointmentResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkGetAppointmentResponseValue200ApplicationJson.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_sdk_get_appointment_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": "00000000-0000-0000-0000-000000000000",
                "product_id": 1,
                "product_variant_id": 1,
                "order_id": 1,
                "invoice_id": 1,
                "customer_id": 1,
                "customer_email": "test@example.com",
                "slot_start_at": "2023-01-01T00:00:00.000Z",
                "slot_end_at": "2023-01-01T00:00:00.000Z",
                "timezone": "Europe/London",
                "quantity": 1,
                "status": "pending",
                "calendar_sync_status": "pending",
                "external_event_link": "test_external_event_link",
                "video_join_url": "video_join_url_01234",
                "confirmed_at": "2023-01-01T00:00:00.000Z",
                "cancelled_at": "2023-01-01T00:00:00.000Z",
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "product": {"id": 1, "title": "test_title"},
                "variant": {"id": 1, "title": "test_title"},
            }
        }
        instance = SdkGetAppointmentResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_update_appointment_response_value_200_application_json_property_data_property_product_round_trip(
        self,
    ):
        data = load_fixture(
            "update_appointment_response_value_200_application_json_property_data_property_product.json"
        )
        instance = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_update_appointment_response_value_200_application_json_property_data_property_product_minimal_payload(
        self,
    ):
        data = {}
        instance = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_update_appointment_response_value_200_application_json_property_data_property_product_preserves_nullable_fields(
        self,
    ):
        data = {"id": None, "title": None}
        instance = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] is None
        assert serialized["title"] is None

    def test_update_appointment_response_value_200_application_json_property_data_property_variant_round_trip(
        self,
    ):
        data = load_fixture(
            "update_appointment_response_value_200_application_json_property_data_property_variant.json"
        )
        instance = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_update_appointment_response_value_200_application_json_property_data_property_variant_minimal_payload(
        self,
    ):
        data = {}
        instance = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_update_appointment_response_value_200_application_json_property_data_property_variant_preserves_nullable_fields(
        self,
    ):
        data = {"id": None, "title": None}
        instance = UpdateAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] is None
        assert serialized["title"] is None

    def test_update_appointment_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "update_appointment_response_value_200_application_json_property_data.json"
        )
        instance = (
            UpdateAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            UpdateAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_update_appointment_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": None,
            "customer_email": None,
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "pending",
            "calendar_sync_status": "pending",
            "external_event_link": None,
            "video_join_url": None,
            "confirmed_at": None,
            "cancelled_at": None,
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": None,
            "variant": None,
        }
        instance = (
            UpdateAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["product_id"] == data["product_id"]
        assert serialized["product_variant_id"] == data["product_variant_id"]
        assert serialized["order_id"] == data["order_id"]
        assert serialized["invoice_id"] == data["invoice_id"]
        assert serialized["customer_id"] == data["customer_id"]
        assert serialized["customer_email"] == data["customer_email"]
        assert serialized["slot_start_at"] == data["slot_start_at"]
        assert serialized["slot_end_at"] == data["slot_end_at"]
        assert serialized["timezone"] == data["timezone"]
        assert serialized["quantity"] == data["quantity"]
        assert serialized["status"] == data["status"]
        assert serialized["calendar_sync_status"] == data["calendar_sync_status"]
        assert serialized["external_event_link"] == data["external_event_link"]
        assert serialized["video_join_url"] == data["video_join_url"]
        assert serialized["confirmed_at"] == data["confirmed_at"]
        assert serialized["cancelled_at"] == data["cancelled_at"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["product"] == data["product"]
        assert serialized["variant"] == data["variant"]

    def test_update_appointment_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": None,
            "customer_email": None,
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "pending",
            "calendar_sync_status": "pending",
            "external_event_link": None,
            "video_join_url": None,
            "confirmed_at": None,
            "cancelled_at": None,
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": None,
            "variant": None,
        }
        instance = (
            UpdateAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["customer_id"] is None
        assert serialized["customer_email"] is None
        assert serialized["external_event_link"] is None
        assert serialized["video_join_url"] is None
        assert serialized["confirmed_at"] is None
        assert serialized["cancelled_at"] is None
        assert serialized["product"] is None
        assert serialized["variant"] is None

    def test_update_appointment_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": 1,
            "customer_email": "test@example.com",
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "unexpected_update_appointment_response_value_200_application_json_property_data_status",
            "calendar_sync_status": "pending",
            "external_event_link": "test_external_event_link",
            "video_join_url": "video_join_url_01234",
            "confirmed_at": "2023-01-01T00:00:00.000Z",
            "cancelled_at": "2023-01-01T00:00:00.000Z",
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": {"id": 1, "title": "test_title"},
            "variant": {"id": 1, "title": "test_title"},
        }
        instance = (
            UpdateAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        assert instance.to_dict() == data

    def test_sdk_update_appointment_response_value_200_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_update_appointment_response_value_200_application_json.json"
        )
        instance = SdkUpdateAppointmentResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkUpdateAppointmentResponseValue200ApplicationJson.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_sdk_update_appointment_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": "00000000-0000-0000-0000-000000000000",
                "product_id": 1,
                "product_variant_id": 1,
                "order_id": 1,
                "invoice_id": 1,
                "customer_id": 1,
                "customer_email": "test@example.com",
                "slot_start_at": "2023-01-01T00:00:00.000Z",
                "slot_end_at": "2023-01-01T00:00:00.000Z",
                "timezone": "Europe/London",
                "quantity": 1,
                "status": "pending",
                "calendar_sync_status": "pending",
                "external_event_link": "test_external_event_link",
                "video_join_url": "video_join_url_01234",
                "confirmed_at": "2023-01-01T00:00:00.000Z",
                "cancelled_at": "2023-01-01T00:00:00.000Z",
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "product": {"id": 1, "title": "test_title"},
                "variant": {"id": 1, "title": "test_title"},
            }
        }
        instance = SdkUpdateAppointmentResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_cancel_appointment_response_value_200_application_json_property_data_property_product_round_trip(
        self,
    ):
        data = load_fixture(
            "cancel_appointment_response_value_200_application_json_property_data_property_product.json"
        )
        instance = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_cancel_appointment_response_value_200_application_json_property_data_property_product_minimal_payload(
        self,
    ):
        data = {}
        instance = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_cancel_appointment_response_value_200_application_json_property_data_property_product_preserves_nullable_fields(
        self,
    ):
        data = {"id": None, "title": None}
        instance = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] is None
        assert serialized["title"] is None

    def test_cancel_appointment_response_value_200_application_json_property_data_property_variant_round_trip(
        self,
    ):
        data = load_fixture(
            "cancel_appointment_response_value_200_application_json_property_data_property_variant.json"
        )
        instance = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_cancel_appointment_response_value_200_application_json_property_data_property_variant_minimal_payload(
        self,
    ):
        data = {}
        instance = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        assert instance.to_dict() is not None

    def test_cancel_appointment_response_value_200_application_json_property_data_property_variant_preserves_nullable_fields(
        self,
    ):
        data = {"id": None, "title": None}
        instance = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] is None
        assert serialized["title"] is None

    def test_cancel_appointment_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "cancel_appointment_response_value_200_application_json_property_data.json"
        )
        instance = (
            CancelAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            CancelAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_cancel_appointment_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": None,
            "customer_email": None,
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "pending",
            "calendar_sync_status": "pending",
            "external_event_link": None,
            "video_join_url": None,
            "confirmed_at": None,
            "cancelled_at": None,
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": None,
            "variant": None,
        }
        instance = (
            CancelAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["product_id"] == data["product_id"]
        assert serialized["product_variant_id"] == data["product_variant_id"]
        assert serialized["order_id"] == data["order_id"]
        assert serialized["invoice_id"] == data["invoice_id"]
        assert serialized["customer_id"] == data["customer_id"]
        assert serialized["customer_email"] == data["customer_email"]
        assert serialized["slot_start_at"] == data["slot_start_at"]
        assert serialized["slot_end_at"] == data["slot_end_at"]
        assert serialized["timezone"] == data["timezone"]
        assert serialized["quantity"] == data["quantity"]
        assert serialized["status"] == data["status"]
        assert serialized["calendar_sync_status"] == data["calendar_sync_status"]
        assert serialized["external_event_link"] == data["external_event_link"]
        assert serialized["video_join_url"] == data["video_join_url"]
        assert serialized["confirmed_at"] == data["confirmed_at"]
        assert serialized["cancelled_at"] == data["cancelled_at"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]
        assert serialized["product"] == data["product"]
        assert serialized["variant"] == data["variant"]

    def test_cancel_appointment_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": None,
            "customer_email": None,
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "pending",
            "calendar_sync_status": "pending",
            "external_event_link": None,
            "video_join_url": None,
            "confirmed_at": None,
            "cancelled_at": None,
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": None,
            "variant": None,
        }
        instance = (
            CancelAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["customer_id"] is None
        assert serialized["customer_email"] is None
        assert serialized["external_event_link"] is None
        assert serialized["video_join_url"] is None
        assert serialized["confirmed_at"] is None
        assert serialized["cancelled_at"] is None
        assert serialized["product"] is None
        assert serialized["variant"] is None

    def test_cancel_appointment_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "order_id": 1,
            "invoice_id": 1,
            "customer_id": 1,
            "customer_email": "test@example.com",
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "Europe/London",
            "quantity": 1,
            "status": "unexpected_cancel_appointment_response_value_200_application_json_property_data_status",
            "calendar_sync_status": "pending",
            "external_event_link": "test_external_event_link",
            "video_join_url": "video_join_url_01234",
            "confirmed_at": "2023-01-01T00:00:00.000Z",
            "cancelled_at": "2023-01-01T00:00:00.000Z",
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
            "product": {"id": 1, "title": "test_title"},
            "variant": {"id": 1, "title": "test_title"},
        }
        instance = (
            CancelAppointmentResponseValue200ApplicationJsonPropertyData.from_dict(data)
        )
        assert instance.to_dict() == data

    def test_sdk_cancel_appointment_response_value_200_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_cancel_appointment_response_value_200_application_json.json"
        )
        instance = SdkCancelAppointmentResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkCancelAppointmentResponseValue200ApplicationJson.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_sdk_cancel_appointment_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "id": "00000000-0000-0000-0000-000000000000",
                "product_id": 1,
                "product_variant_id": 1,
                "order_id": 1,
                "invoice_id": 1,
                "customer_id": 1,
                "customer_email": "test@example.com",
                "slot_start_at": "2023-01-01T00:00:00.000Z",
                "slot_end_at": "2023-01-01T00:00:00.000Z",
                "timezone": "Europe/London",
                "quantity": 1,
                "status": "pending",
                "calendar_sync_status": "pending",
                "external_event_link": "test_external_event_link",
                "video_join_url": "video_join_url_01234",
                "confirmed_at": "2023-01-01T00:00:00.000Z",
                "cancelled_at": "2023-01-01T00:00:00.000Z",
                "created_at": "2023-01-01T00:00:00.000Z",
                "updated_at": "2023-01-01T00:00:00.000Z",
                "product": {"id": 1, "title": "test_title"},
                "variant": {"id": 1, "title": "test_title"},
            }
        }
        instance = SdkCancelAppointmentResponseValue200ApplicationJson.from_dict(data)
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_get_booking_configuration_response_value_200_application_json_property_data_property_availability_item_round_trip(
        self,
    ):
        data = load_fixture(
            "get_booking_configuration_response_value_200_application_json_property_data_property_availability_item.json"
        )
        instance = GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_get_booking_configuration_response_value_200_application_json_property_data_property_availability_item_minimal_payload(
        self,
    ):
        data = {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"}
        instance = GetBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["day"] == data["day"]
        assert serialized["enabled"] == data["enabled"]
        assert serialized["start"] == data["start"]
        assert serialized["end"] == data["end"]

    def test_get_booking_configuration_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "get_booking_configuration_response_value_200_application_json_property_data.json"
        )
        instance = GetBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = GetBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_get_booking_configuration_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "product",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": None,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = GetBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["product_id"] == data["product_id"]
        assert serialized["product_variant_id"] == data["product_variant_id"]
        assert serialized["mode"] == data["mode"]
        assert serialized["conflict_scope"] == data["conflict_scope"]
        assert serialized["timezone"] == data["timezone"]
        assert serialized["duration_minutes"] == data["duration_minutes"]
        assert serialized["capacity_per_slot"] == data["capacity_per_slot"]
        assert serialized["min_notice_minutes"] == data["min_notice_minutes"]
        assert serialized["max_advance_days"] == data["max_advance_days"]
        assert serialized["buffer_before_minutes"] == data["buffer_before_minutes"]
        assert serialized["buffer_after_minutes"] == data["buffer_after_minutes"]
        assert serialized["availability"] == data["availability"]
        assert serialized["provider_connection_ids"] == data["provider_connection_ids"]
        assert serialized["video_provider"] == data["video_provider"]
        assert (
            serialized["video_provider_connection_id"]
            == data["video_provider_connection_id"]
        )
        assert serialized["reminders_enabled"] == data["reminders_enabled"]
        assert serialized["reminder_offset_value"] == data["reminder_offset_value"]
        assert serialized["reminder_offset_unit"] == data["reminder_offset_unit"]
        assert serialized["meta"] == data["meta"]

    def test_get_booking_configuration_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "product",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": None,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = GetBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["video_provider_connection_id"] is None

    def test_get_booking_configuration_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "unexpected_get_booking_configuration_response_value_200_application_json_property_data_conflict_scope",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": 1,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = GetBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_get_booking_configuration_response_value_200_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_get_booking_configuration_response_value_200_application_json.json"
        )
        instance = SdkGetBookingConfigurationResponseValue200ApplicationJson.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = SdkGetBookingConfigurationResponseValue200ApplicationJson.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_sdk_get_booking_configuration_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "product_id": 1,
                "product_variant_id": 1,
                "mode": "native",
                "conflict_scope": "product",
                "timezone": "America/New_York",
                "duration_minutes": 30,
                "capacity_per_slot": 1,
                "min_notice_minutes": 1,
                "max_advance_days": 1,
                "buffer_before_minutes": 30,
                "buffer_after_minutes": 30,
                "availability": [
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                ],
                "provider_connection_ids": [1],
                "video_provider": "none",
                "video_provider_connection_id": 1,
                "reminders_enabled": True,
                "reminder_offset_value": 1,
                "reminder_offset_unit": "minutes",
                "meta": {},
            }
        }
        instance = SdkGetBookingConfigurationResponseValue200ApplicationJson.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_replace_booking_configuration_request_application_json_property_availability_item_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_booking_configuration_request_application_json_property_availability_item.json"
        )
        instance = ReplaceBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_booking_configuration_request_application_json_property_availability_item_minimal_payload(
        self,
    ):
        data = {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"}
        instance = ReplaceBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["day"] == data["day"]
        assert serialized["enabled"] == data["enabled"]
        assert serialized["start"] == data["start"]
        assert serialized["end"] == data["end"]

    def test_replace_booking_configuration_response_value_200_application_json_property_data_property_availability_item_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_booking_configuration_response_value_200_application_json_property_data_property_availability_item.json"
        )
        instance = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_booking_configuration_response_value_200_application_json_property_data_property_availability_item_minimal_payload(
        self,
    ):
        data = {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"}
        instance = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["day"] == data["day"]
        assert serialized["enabled"] == data["enabled"]
        assert serialized["start"] == data["start"]
        assert serialized["end"] == data["end"]

    def test_replace_booking_configuration_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "replace_booking_configuration_response_value_200_application_json_property_data.json"
        )
        instance = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_replace_booking_configuration_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "product",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": None,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["product_id"] == data["product_id"]
        assert serialized["product_variant_id"] == data["product_variant_id"]
        assert serialized["mode"] == data["mode"]
        assert serialized["conflict_scope"] == data["conflict_scope"]
        assert serialized["timezone"] == data["timezone"]
        assert serialized["duration_minutes"] == data["duration_minutes"]
        assert serialized["capacity_per_slot"] == data["capacity_per_slot"]
        assert serialized["min_notice_minutes"] == data["min_notice_minutes"]
        assert serialized["max_advance_days"] == data["max_advance_days"]
        assert serialized["buffer_before_minutes"] == data["buffer_before_minutes"]
        assert serialized["buffer_after_minutes"] == data["buffer_after_minutes"]
        assert serialized["availability"] == data["availability"]
        assert serialized["provider_connection_ids"] == data["provider_connection_ids"]
        assert serialized["video_provider"] == data["video_provider"]
        assert (
            serialized["video_provider_connection_id"]
            == data["video_provider_connection_id"]
        )
        assert serialized["reminders_enabled"] == data["reminders_enabled"]
        assert serialized["reminder_offset_value"] == data["reminder_offset_value"]
        assert serialized["reminder_offset_unit"] == data["reminder_offset_unit"]
        assert serialized["meta"] == data["meta"]

    def test_replace_booking_configuration_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "product",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": None,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["video_provider_connection_id"] is None

    def test_replace_booking_configuration_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "unexpected_replace_booking_configuration_response_value_200_application_json_property_data_conflict_scope",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": 1,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_replace_booking_configuration_response_value_200_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_replace_booking_configuration_response_value_200_application_json.json"
        )
        instance = (
            SdkReplaceBookingConfigurationResponseValue200ApplicationJson.from_dict(
                data
            )
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            SdkReplaceBookingConfigurationResponseValue200ApplicationJson.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_sdk_replace_booking_configuration_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "product_id": 1,
                "product_variant_id": 1,
                "mode": "native",
                "conflict_scope": "product",
                "timezone": "America/New_York",
                "duration_minutes": 30,
                "capacity_per_slot": 1,
                "min_notice_minutes": 1,
                "max_advance_days": 1,
                "buffer_before_minutes": 30,
                "buffer_after_minutes": 30,
                "availability": [
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                ],
                "provider_connection_ids": [1],
                "video_provider": "none",
                "video_provider_connection_id": 1,
                "reminders_enabled": True,
                "reminder_offset_value": 1,
                "reminder_offset_unit": "minutes",
                "meta": {},
            }
        }
        instance = (
            SdkReplaceBookingConfigurationResponseValue200ApplicationJson.from_dict(
                data
            )
        )
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_update_booking_configuration_request_application_json_property_availability_item_round_trip(
        self,
    ):
        data = load_fixture(
            "update_booking_configuration_request_application_json_property_availability_item.json"
        )
        instance = UpdateBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = UpdateBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_update_booking_configuration_request_application_json_property_availability_item_minimal_payload(
        self,
    ):
        data = {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"}
        instance = UpdateBookingConfigurationRequestApplicationJsonPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["day"] == data["day"]
        assert serialized["enabled"] == data["enabled"]
        assert serialized["start"] == data["start"]
        assert serialized["end"] == data["end"]

    def test_update_booking_configuration_response_value_200_application_json_property_data_property_availability_item_round_trip(
        self,
    ):
        data = load_fixture(
            "update_booking_configuration_response_value_200_application_json_property_data_property_availability_item.json"
        )
        instance = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_update_booking_configuration_response_value_200_application_json_property_data_property_availability_item_minimal_payload(
        self,
    ):
        data = {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"}
        instance = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyDataPropertyAvailabilityItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["day"] == data["day"]
        assert serialized["enabled"] == data["enabled"]
        assert serialized["start"] == data["start"]
        assert serialized["end"] == data["end"]

    def test_update_booking_configuration_response_value_200_application_json_property_data_round_trip(
        self,
    ):
        data = load_fixture(
            "update_booking_configuration_response_value_200_application_json_property_data.json"
        )
        instance = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_update_booking_configuration_response_value_200_application_json_property_data_minimal_payload(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "product",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": None,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["product_id"] == data["product_id"]
        assert serialized["product_variant_id"] == data["product_variant_id"]
        assert serialized["mode"] == data["mode"]
        assert serialized["conflict_scope"] == data["conflict_scope"]
        assert serialized["timezone"] == data["timezone"]
        assert serialized["duration_minutes"] == data["duration_minutes"]
        assert serialized["capacity_per_slot"] == data["capacity_per_slot"]
        assert serialized["min_notice_minutes"] == data["min_notice_minutes"]
        assert serialized["max_advance_days"] == data["max_advance_days"]
        assert serialized["buffer_before_minutes"] == data["buffer_before_minutes"]
        assert serialized["buffer_after_minutes"] == data["buffer_after_minutes"]
        assert serialized["availability"] == data["availability"]
        assert serialized["provider_connection_ids"] == data["provider_connection_ids"]
        assert serialized["video_provider"] == data["video_provider"]
        assert (
            serialized["video_provider_connection_id"]
            == data["video_provider_connection_id"]
        )
        assert serialized["reminders_enabled"] == data["reminders_enabled"]
        assert serialized["reminder_offset_value"] == data["reminder_offset_value"]
        assert serialized["reminder_offset_unit"] == data["reminder_offset_unit"]
        assert serialized["meta"] == data["meta"]

    def test_update_booking_configuration_response_value_200_application_json_property_data_preserves_nullable_fields(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "product",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": None,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["video_provider_connection_id"] is None

    def test_update_booking_configuration_response_value_200_application_json_property_data_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "product_id": 1,
            "product_variant_id": 1,
            "mode": "native",
            "conflict_scope": "unexpected_update_booking_configuration_response_value_200_application_json_property_data_conflict_scope",
            "timezone": "America/New_York",
            "duration_minutes": 30,
            "capacity_per_slot": 1,
            "min_notice_minutes": 1,
            "max_advance_days": 1,
            "buffer_before_minutes": 30,
            "buffer_after_minutes": 30,
            "availability": [
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
            ],
            "provider_connection_ids": [1],
            "video_provider": "none",
            "video_provider_connection_id": 1,
            "reminders_enabled": True,
            "reminder_offset_value": 1,
            "reminder_offset_unit": "minutes",
            "meta": {},
        }
        instance = UpdateBookingConfigurationResponseValue200ApplicationJsonPropertyData.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_update_booking_configuration_response_value_200_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_update_booking_configuration_response_value_200_application_json.json"
        )
        instance = (
            SdkUpdateBookingConfigurationResponseValue200ApplicationJson.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            SdkUpdateBookingConfigurationResponseValue200ApplicationJson.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_sdk_update_booking_configuration_response_value_200_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": {
                "product_id": 1,
                "product_variant_id": 1,
                "mode": "native",
                "conflict_scope": "product",
                "timezone": "America/New_York",
                "duration_minutes": 30,
                "capacity_per_slot": 1,
                "min_notice_minutes": 1,
                "max_advance_days": 1,
                "buffer_before_minutes": 30,
                "buffer_after_minutes": 30,
                "availability": [
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                    {"day": 1, "enabled": True, "start": "09:00", "end": "17:00"},
                ],
                "provider_connection_ids": [1],
                "video_provider": "none",
                "video_provider_connection_id": 1,
                "reminders_enabled": True,
                "reminder_offset_value": 1,
                "reminder_offset_unit": "minutes",
                "meta": {},
            }
        }
        instance = (
            SdkUpdateBookingConfigurationResponseValue200ApplicationJson.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]

    def test_set_booking_date_availability_response_value_201_application_json_property_data_item_round_trip(
        self,
    ):
        data = load_fixture(
            "set_booking_date_availability_response_value_201_application_json_property_data_item.json"
        )
        instance = SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItem.from_dict(
            serialized
        )
        assert restored.to_dict() == serialized

    def test_set_booking_date_availability_response_value_201_application_json_property_data_item_minimal_payload(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": None,
            "product_variant_id": None,
            "type": "blocked",
            "status": "active",
            "title": "test_title",
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "test_timezone",
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
        }
        instance = SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["id"] == data["id"]
        assert serialized["product_id"] == data["product_id"]
        assert serialized["product_variant_id"] == data["product_variant_id"]
        assert serialized["type"] == data["type"]
        assert serialized["status"] == data["status"]
        assert serialized["title"] == data["title"]
        assert serialized["slot_start_at"] == data["slot_start_at"]
        assert serialized["slot_end_at"] == data["slot_end_at"]
        assert serialized["timezone"] == data["timezone"]
        assert serialized["created_at"] == data["created_at"]
        assert serialized["updated_at"] == data["updated_at"]

    def test_set_booking_date_availability_response_value_201_application_json_property_data_item_preserves_nullable_fields(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": None,
            "product_variant_id": None,
            "type": "blocked",
            "status": "active",
            "title": "test_title",
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "test_timezone",
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
        }
        instance = SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        serialized = instance.to_dict()
        assert serialized["product_id"] is None
        assert serialized["product_variant_id"] is None

    def test_set_booking_date_availability_response_value_201_application_json_property_data_item_round_trips_unknown_enum_values(
        self,
    ):
        data = {
            "id": "00000000-0000-0000-0000-000000000000",
            "product_id": 1,
            "product_variant_id": 1,
            "type": "unexpected_set_booking_date_availability_response_value_201_application_json_property_data_item_type",
            "status": "active",
            "title": "test_title",
            "slot_start_at": "2023-01-01T00:00:00.000Z",
            "slot_end_at": "2023-01-01T00:00:00.000Z",
            "timezone": "test_timezone",
            "created_at": "2023-01-01T00:00:00.000Z",
            "updated_at": "2023-01-01T00:00:00.000Z",
        }
        instance = SetBookingDateAvailabilityResponseValue201ApplicationJsonPropertyDataItem.from_dict(
            data
        )
        assert instance.to_dict() == data

    def test_sdk_set_booking_date_availability_response_value_201_application_json_round_trip(
        self,
    ):
        data = load_fixture(
            "sdk_set_booking_date_availability_response_value_201_application_json.json"
        )
        instance = (
            SdkSetBookingDateAvailabilityResponseValue201ApplicationJson.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized == data
        restored = (
            SdkSetBookingDateAvailabilityResponseValue201ApplicationJson.from_dict(
                serialized
            )
        )
        assert restored.to_dict() == serialized

    def test_sdk_set_booking_date_availability_response_value_201_application_json_minimal_payload(
        self,
    ):
        data = {
            "data": [
                {
                    "id": "00000000-0000-0000-0000-000000000000",
                    "product_id": 1,
                    "product_variant_id": 1,
                    "type": "blocked",
                    "status": "active",
                    "title": "test_title",
                    "slot_start_at": "2023-01-01T00:00:00.000Z",
                    "slot_end_at": "2023-01-01T00:00:00.000Z",
                    "timezone": "test_timezone",
                    "created_at": "2023-01-01T00:00:00.000Z",
                    "updated_at": "2023-01-01T00:00:00.000Z",
                }
            ]
        }
        instance = (
            SdkSetBookingDateAvailabilityResponseValue201ApplicationJson.from_dict(data)
        )
        serialized = instance.to_dict()
        assert serialized["data"] == data["data"]
