# This file is auto-generated by oagen. Do not edit.

import json

import pytest

from sellapp_sdk import AsyncSellAppClient, SellAppClient
from sellapp_sdk._errors import (
    AuthenticationError,
    BadRequestError,
    NotFoundError,
    RateLimitExceededError,
    ServerError,
    UnprocessableEntityError,
)
from sellapp_sdk.cashback_rules.models import (
    SdkCreateCashbackRuleResponseValue201ApplicationJson,
    SdkListCashbackRulesResponseValue200ApplicationJson,
    SdkReplaceCashbackRuleResponseValue200ApplicationJson,
    SdkRestoreCashbackRuleResponseValue200ApplicationJson,
    SdkUpdateCashbackRuleResponseValue200ApplicationJson,
)
from tests.generated_helpers import load_fixture


class TestCashbackRules:
    def test_list(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_list_cashback_rules_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.cashback_rules.list()
        assert isinstance(result, SdkListCashbackRulesResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/v2/cashback-rules")

    def test_create(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_create_cashback_rule_response_value_201_application_json.json"
            ),
        )
        result = sellapp_sdk.cashback_rules.create(
            percent_basis=1, maximum_cashback_cents=1, is_active=True, product_ids=[1]
        )
        assert isinstance(result, SdkCreateCashbackRuleResponseValue201ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/v2/cashback-rules")
        body = json.loads(request.content)
        assert body["percent_basis"] == 1
        assert "maximum_cashback_cents" in body
        assert body["is_active"] == True
        assert "product_ids" in body

    def test_replace(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_replace_cashback_rule_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.cashback_rules.replace(
            "test_cashbackRule",
            percent_basis=1,
            maximum_cashback_cents=1,
            is_active=True,
            product_ids=[1],
        )
        assert isinstance(result, SdkReplaceCashbackRuleResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule")
        body = json.loads(request.content)
        assert body["percent_basis"] == 1
        assert "maximum_cashback_cents" in body
        assert body["is_active"] == True
        assert "product_ids" in body

    def test_update(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_update_cashback_rule_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.cashback_rules.update("test_cashbackRule")
        assert isinstance(result, SdkUpdateCashbackRuleResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PATCH"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule")

    def test_archive(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(status_code=200, content=b"")
        result = sellapp_sdk.cashback_rules.archive("test_cashbackRule")
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule")

    def test_restore(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_restore_cashback_rule_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.cashback_rules.restore("test_cashbackRule")
        assert isinstance(result, SdkRestoreCashbackRuleResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule/restore")

    def test_list_with_request_options(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_list_cashback_rules_response_value_200_application_json.json"
            )
        )
        sellapp_sdk.cashback_rules.list(
            request_options={"headers": {"X-Custom": "value"}}
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    def test_list_unauthorized(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Unauthorized"},
        )
        with pytest.raises(AuthenticationError):
            sellapp_sdk.cashback_rules.list()

    def test_list_not_found(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                sellapp_sdk.cashback_rules.list()
        finally:
            sellapp_sdk.close()

    def test_list_rate_limited(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                sellapp_sdk.cashback_rules.list()
        finally:
            sellapp_sdk.close()

    def test_list_server_error(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                sellapp_sdk.cashback_rules.list()
        finally:
            sellapp_sdk.close()

    def test_list_bad_request(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                sellapp_sdk.cashback_rules.list()
        finally:
            sellapp_sdk.close()

    def test_list_unprocessable(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                sellapp_sdk.cashback_rules.list()
        finally:
            sellapp_sdk.close()


class TestAsyncCashbackRules:
    @pytest.mark.asyncio
    async def test_list(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_list_cashback_rules_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.cashback_rules.list()
        assert isinstance(result, SdkListCashbackRulesResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/v2/cashback-rules")

    @pytest.mark.asyncio
    async def test_create(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_create_cashback_rule_response_value_201_application_json.json"
            )
        )
        result = await async_sellapp_sdk.cashback_rules.create(
            percent_basis=1, maximum_cashback_cents=1, is_active=True, product_ids=[1]
        )
        assert isinstance(result, SdkCreateCashbackRuleResponseValue201ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/v2/cashback-rules")

    @pytest.mark.asyncio
    async def test_replace(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_replace_cashback_rule_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.cashback_rules.replace(
            "test_cashbackRule",
            percent_basis=1,
            maximum_cashback_cents=1,
            is_active=True,
            product_ids=[1],
        )
        assert isinstance(result, SdkReplaceCashbackRuleResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule")

    @pytest.mark.asyncio
    async def test_update(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_update_cashback_rule_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.cashback_rules.update("test_cashbackRule")
        assert isinstance(result, SdkUpdateCashbackRuleResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PATCH"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule")

    @pytest.mark.asyncio
    async def test_archive(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(status_code=200, content=b"")
        result = await async_sellapp_sdk.cashback_rules.archive("test_cashbackRule")
        assert result is None
        request = httpx_mock.get_request()
        assert request.method == "DELETE"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule")

    @pytest.mark.asyncio
    async def test_restore(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_restore_cashback_rule_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.cashback_rules.restore("test_cashbackRule")
        assert isinstance(result, SdkRestoreCashbackRuleResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/v2/cashback-rules/test_cashbackRule/restore")

    @pytest.mark.asyncio
    async def test_list_with_request_options(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_list_cashback_rules_response_value_200_application_json.json"
            )
        )
        await async_sellapp_sdk.cashback_rules.list(
            request_options={"headers": {"X-Custom": "value"}}
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    @pytest.mark.asyncio
    async def test_list_unauthorized(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(status_code=401, json={"message": "Unauthorized"})
        with pytest.raises(AuthenticationError):
            await async_sellapp_sdk.cashback_rules.list()

    @pytest.mark.asyncio
    async def test_list_not_found(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                await sellapp_sdk.cashback_rules.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_rate_limited(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                await sellapp_sdk.cashback_rules.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_server_error(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                await sellapp_sdk.cashback_rules.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_bad_request(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                await sellapp_sdk.cashback_rules.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_unprocessable(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                await sellapp_sdk.cashback_rules.list()
        finally:
            await sellapp_sdk.close()
