# This file is auto-generated by oagen. Do not edit.

import json

import pytest

from sellapp_sdk import AsyncSellAppClient, SellAppClient
from sellapp_sdk._errors import (
    AuthenticationError,
    BadRequestError,
    NotFoundError,
    RateLimitExceededError,
    ServerError,
    UnprocessableEntityError,
)
from sellapp_sdk._pagination import AsyncPage, SyncPage
from sellapp_sdk.common.models import (
    SdkCreateCustomerResponseValue201ApplicationJson,
)
from sellapp_sdk.customers.models import (
    SdkGetCustomerResponseValue200ApplicationJson,
    SdkUpdateCustomerResponseValue200ApplicationJson,
    SdkUpsertCustomerResponseValue200ApplicationJson,
)
from tests.generated_helpers import load_fixture


class TestCustomers:
    def test_list(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = sellapp_sdk.customers.list()
        assert isinstance(page, SyncPage)

    def test_list_encodes_query_params(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        sellapp_sdk.customers.list(
            limit=10,
            before="cursor before",
            after="cursor/after",
            page=7,
            pagination=True,
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["page"] == "7"
        assert request.url.params["pagination"] == "true"

    def test_create_customer(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_create_customer_response_value_201_application_json.json"
            ),
        )
        result = sellapp_sdk.customers.create_customer(email="test_email")
        assert isinstance(result, SdkCreateCustomerResponseValue201ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/v2/customers")
        body = json.loads(request.content)
        assert body["email"] == "test_email"

    def test_search(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = sellapp_sdk.customers.search()
        assert isinstance(page, SyncPage)

    def test_search_encodes_query_params(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        sellapp_sdk.customers.search(
            limit=10,
            before="cursor before",
            after="cursor/after",
            page=7,
            pagination=True,
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["page"] == "7"
        assert request.url.params["pagination"] == "true"

    def test_get(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_get_customer_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.customers.get("test_customer")
        assert isinstance(result, SdkGetCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/v2/customers/test_customer")

    def test_update_customer(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_update_customer_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.customers.update_customer("test_customer")
        assert isinstance(result, SdkUpdateCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PATCH"
        assert request.url.path.endswith("/v2/customers/test_customer")

    def test_get_customer_by_external_id(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_get_customer_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.customers.get_customer_by_external_id("test_externalId")
        assert isinstance(result, SdkGetCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/v2/customers/external/test_externalId")

    def test_upsert_by_external_id(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_upsert_customer_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.customers.upsert_by_external_id(
            "test_externalId", email="test_email"
        )
        assert isinstance(result, SdkUpsertCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith("/v2/customers/external/test_externalId")
        body = json.loads(request.content)
        assert body["email"] == "test_email"

    def test_update_customer_by_external_id(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_update_customer_response_value_200_application_json.json"
            ),
        )
        result = sellapp_sdk.customers.update_customer_by_external_id("test_externalId")
        assert isinstance(result, SdkUpdateCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PATCH"
        assert request.url.path.endswith("/v2/customers/external/test_externalId")

    def test_list_with_request_options(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        sellapp_sdk.customers.list(request_options={"headers": {"X-Custom": "value"}})
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    def test_list_unauthorized(self, sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            status_code=401,
            json={"message": "Unauthorized"},
        )
        with pytest.raises(AuthenticationError):
            sellapp_sdk.customers.list()

    def test_list_not_found(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                sellapp_sdk.customers.list()
        finally:
            sellapp_sdk.close()

    def test_list_rate_limited(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                sellapp_sdk.customers.list()
        finally:
            sellapp_sdk.close()

    def test_list_server_error(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                sellapp_sdk.customers.list()
        finally:
            sellapp_sdk.close()

    def test_list_bad_request(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                sellapp_sdk.customers.list()
        finally:
            sellapp_sdk.close()

    def test_list_unprocessable(self, httpx_mock):
        sellapp_sdk = SellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                sellapp_sdk.customers.list()
        finally:
            sellapp_sdk.close()


class TestAsyncCustomers:
    @pytest.mark.asyncio
    async def test_list(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = await async_sellapp_sdk.customers.list()
        assert isinstance(page, AsyncPage)

    @pytest.mark.asyncio
    async def test_list_encodes_query_params(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_sellapp_sdk.customers.list(
            limit=10,
            before="cursor before",
            after="cursor/after",
            page=7,
            pagination=True,
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["page"] == "7"
        assert request.url.params["pagination"] == "true"

    @pytest.mark.asyncio
    async def test_create_customer(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_create_customer_response_value_201_application_json.json"
            )
        )
        result = await async_sellapp_sdk.customers.create_customer(email="test_email")
        assert isinstance(result, SdkCreateCustomerResponseValue201ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "POST"
        assert request.url.path.endswith("/v2/customers")

    @pytest.mark.asyncio
    async def test_search(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        page = await async_sellapp_sdk.customers.search()
        assert isinstance(page, AsyncPage)

    @pytest.mark.asyncio
    async def test_search_encodes_query_params(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_sellapp_sdk.customers.search(
            limit=10,
            before="cursor before",
            after="cursor/after",
            page=7,
            pagination=True,
        )
        request = httpx_mock.get_request()
        assert request.url.params["limit"] == "10"
        assert request.url.params["before"] == "cursor before"
        assert request.url.params["after"] == "cursor/after"
        assert request.url.params["page"] == "7"
        assert request.url.params["pagination"] == "true"

    @pytest.mark.asyncio
    async def test_get(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_get_customer_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.customers.get("test_customer")
        assert isinstance(result, SdkGetCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/v2/customers/test_customer")

    @pytest.mark.asyncio
    async def test_update_customer(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_update_customer_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.customers.update_customer("test_customer")
        assert isinstance(result, SdkUpdateCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PATCH"
        assert request.url.path.endswith("/v2/customers/test_customer")

    @pytest.mark.asyncio
    async def test_get_customer_by_external_id(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_get_customer_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.customers.get_customer_by_external_id(
            "test_externalId"
        )
        assert isinstance(result, SdkGetCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "GET"
        assert request.url.path.endswith("/v2/customers/external/test_externalId")

    @pytest.mark.asyncio
    async def test_upsert_by_external_id(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_upsert_customer_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.customers.upsert_by_external_id(
            "test_externalId", email="test_email"
        )
        assert isinstance(result, SdkUpsertCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PUT"
        assert request.url.path.endswith("/v2/customers/external/test_externalId")

    @pytest.mark.asyncio
    async def test_update_customer_by_external_id(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(
            json=load_fixture(
                "sdk_update_customer_response_value_200_application_json.json"
            )
        )
        result = await async_sellapp_sdk.customers.update_customer_by_external_id(
            "test_externalId"
        )
        assert isinstance(result, SdkUpdateCustomerResponseValue200ApplicationJson)
        request = httpx_mock.get_request()
        assert request.method == "PATCH"
        assert request.url.path.endswith("/v2/customers/external/test_externalId")

    @pytest.mark.asyncio
    async def test_list_with_request_options(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(json={"data": [], "list_metadata": {}})
        await async_sellapp_sdk.customers.list(
            request_options={"headers": {"X-Custom": "value"}}
        )
        request = httpx_mock.get_request()
        assert request.headers["X-Custom"] == "value"

    @pytest.mark.asyncio
    async def test_list_unauthorized(self, async_sellapp_sdk, httpx_mock):
        httpx_mock.add_response(status_code=401, json={"message": "Unauthorized"})
        with pytest.raises(AuthenticationError):
            await async_sellapp_sdk.customers.list()

    @pytest.mark.asyncio
    async def test_list_not_found(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=404, json={"message": "Not found"})
            with pytest.raises(NotFoundError):
                await sellapp_sdk.customers.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_rate_limited(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(
                status_code=429,
                headers={"Retry-After": "0"},
                json={"message": "Slow down"},
            )
            with pytest.raises(RateLimitExceededError):
                await sellapp_sdk.customers.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_server_error(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=500, json={"message": "Server error"})
            with pytest.raises(ServerError):
                await sellapp_sdk.customers.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_bad_request(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=400, json={"message": "Bad request"})
            with pytest.raises(BadRequestError):
                await sellapp_sdk.customers.list()
        finally:
            await sellapp_sdk.close()

    @pytest.mark.asyncio
    async def test_list_unprocessable(self, httpx_mock):
        sellapp_sdk = AsyncSellAppClient(
            api_key="sk_test_123",
            store="store_test",
            access_token="test-oauth",
            customer_session="test-customer",
            browser_session="sell_session=test",
            max_retries=0,
        )
        try:
            httpx_mock.add_response(status_code=422, json={"message": "Unprocessable"})
            with pytest.raises(UnprocessableEntityError):
                await sellapp_sdk.customers.list()
        finally:
            await sellapp_sdk.close()
