# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from sellapp_sdk.common.models.sdk_list_customer_entitlements_response_value_200_application_json import (
    SdkListCustomerEntitlementsResponseValue200ApplicationJson,
)

SdkListCustomerPortalEntitlementsResponseValue200ApplicationJson: TypeAlias = (
    SdkListCustomerEntitlementsResponseValue200ApplicationJson
)
