# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .sdk_create_charge_response_value_201_application_json import (
    SdkCreateChargeResponseValue201ApplicationJson,
)

SdkGetChargeResponseValue200ApplicationJson: TypeAlias = (
    SdkCreateChargeResponseValue201ApplicationJson
)
