# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .get_booking_configuration_response_value_200_application_json_property_data import (
    GetBookingConfigurationResponseValue200ApplicationJsonPropertyData,
)

ReplaceBookingConfigurationResponseValue200ApplicationJsonPropertyData: TypeAlias = (
    GetBookingConfigurationResponseValue200ApplicationJsonPropertyData
)
