# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from datetime import datetime
from typing import Any

from sellapp_sdk._types import (
    _format_datetime,
    _parse_datetime,
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

_DOMAIN_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "SdkUpdateAppointmentRequestApplicationJson",
    "required": ["slot_start_at"],
    "properties": {
        "slot_start_at": {"kind": "primitive", "type": "string", "format": "date-time"},
        "timezone": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string"},
        },
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "SdkUpdateAppointmentRequestApplicationJson",
    "required": ["slot_start_at"],
    "properties": {
        "slot_start_at": {"kind": "primitive", "type": "string", "format": "date-time"},
        "timezone": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string"},
        },
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class SdkUpdateAppointmentRequestApplicationJson:
    """Sdk Update Appointment Request Application Json model."""

    slot_start_at: datetime
    """A future slot start including an explicit UTC offset."""
    timezone: str | None = None
    """IANA timezone used for appointment display and availability rules."""
    additional_properties: dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> SdkUpdateAppointmentRequestApplicationJson:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                slot_start_at=_parse_datetime(data["slot_start_at"]),
                timezone=data.get("timezone"),
                additional_properties=_preserve_unknown_fields(
                    data, ["slot_start_at", "timezone"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("SdkUpdateAppointmentRequestApplicationJson", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: dict[str, Any] = dict(self.additional_properties)
        _domain_data["slot_start_at"] = self.slot_start_at
        _domain_data["timezone"] = self.timezone
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: dict[str, Any] = dict(self.additional_properties)
        result["slot_start_at"] = _format_datetime(self.slot_start_at)
        if self.timezone is not None:
            result["timezone"] = self.timezone
        else:
            result["timezone"] = None
        return result
