# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .sdk_create_highlight_response_value_201_application_json import (
    SdkCreateHighlightResponseValue201ApplicationJson,
)

SdkReplaceHighlightResponseValue200ApplicationJson: TypeAlias = (
    SdkCreateHighlightResponseValue201ApplicationJson
)
