# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any, Dict, List, cast

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

from .reorder_highlights_response_value_200_application_json_property_data_item import (
    ReorderHighlightsResponseValue200ApplicationJsonPropertyDataItem,
)

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "SdkReorderHighlightsResponseValue200ApplicationJson",
    "required": ["data"],
    "properties": {"data": {"kind": "array", "items": {"kind": "any"}}},
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "SdkReorderHighlightsResponseValue200ApplicationJson",
    "required": ["data"],
    "properties": {"data": {"kind": "array", "items": {"kind": "any"}}},
    "additionalProperties": True,
}


@dataclass(slots=True)
class SdkReorderHighlightsResponseValue200ApplicationJson:
    """Sdk Reorder Highlights Response Value200Application Json model."""

    data: List[ReorderHighlightsResponseValue200ApplicationJsonPropertyDataItem]
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> SdkReorderHighlightsResponseValue200ApplicationJson:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                data=[
                    ReorderHighlightsResponseValue200ApplicationJsonPropertyDataItem.from_dict(
                        cast(Dict[str, Any], item)
                    )
                    for item in cast(list[Any], data["data"])
                ],
                additional_properties=_preserve_unknown_fields(data, ["data"]),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "SdkReorderHighlightsResponseValue200ApplicationJson", e
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        _domain_data["data"] = self.data
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        result["data"] = [item.to_dict() for item in self.data]
        return result
