# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from typing import TYPE_CHECKING

from .._base_client import WithRawResponse

if TYPE_CHECKING:
    from .._client import AsyncSellAppClient, SellAppClient

from .._types import RequestOptions
from .models import SdkGetOAuthInstallationResponseValue200ApplicationJson


class OAuthManagement:
    """O Auth Management API resources."""

    def __init__(self, client: SellAppClient) -> None:
        self._client = client
        self.with_raw_response = WithRawResponse(self)

    def get_oauth_installation(
        self,
        *,
        request_options: RequestOptions | None = None,
    ) -> SdkGetOAuthInstallationResponseValue200ApplicationJson:
        """Read your CLI connection

        Read your active official CLI connection, its account-wide grant model and granted scopes.

        Returns:
            SdkGetOAuthInstallationResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "oauthAccessToken", "scopes": ["admin"]}]
                ],
                "anonymous": False,
                "apiKey": False,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": False,
                "accessTokenRequiresStore": False,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "getOAuthInstallation",
        }
        return self._client.request(
            method="get",
            path=("v2", "oauth", "installation"),
            model=SdkGetOAuthInstallationResponseValue200ApplicationJson,
            request_options=request_options,
        )

    def delete_oauth_installation(
        self,
        *,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Disconnect your CLI connection

        Disconnect your official CLI connection and revoke its authorization codes and token families. Run sellapp login to reconnect.

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "oauthAccessToken", "scopes": ["admin"]}]
                ],
                "anonymous": False,
                "apiKey": False,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": False,
                "accessTokenRequiresStore": False,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "deleteOAuthInstallation",
        }
        self._client.request(
            method="delete",
            path=("v2", "oauth", "installation"),
            request_options=request_options,
        )


class AsyncOAuthManagement:
    """O Auth Management API resources (async)."""

    def __init__(self, client: AsyncSellAppClient) -> None:
        self._client = client
        self.with_raw_response = WithRawResponse(self)

    async def get_oauth_installation(
        self,
        *,
        request_options: RequestOptions | None = None,
    ) -> SdkGetOAuthInstallationResponseValue200ApplicationJson:
        """Read your CLI connection

        Read your active official CLI connection, its account-wide grant model and granted scopes.

        Returns:
            SdkGetOAuthInstallationResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "oauthAccessToken", "scopes": ["admin"]}]
                ],
                "anonymous": False,
                "apiKey": False,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": False,
                "accessTokenRequiresStore": False,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "getOAuthInstallation",
        }
        return await self._client.request(
            method="get",
            path=("v2", "oauth", "installation"),
            model=SdkGetOAuthInstallationResponseValue200ApplicationJson,
            request_options=request_options,
        )

    async def delete_oauth_installation(
        self,
        *,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Disconnect your CLI connection

        Disconnect your official CLI connection and revoke its authorization codes and token families. Run sellapp login to reconnect.

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "oauthAccessToken", "scopes": ["admin"]}]
                ],
                "anonymous": False,
                "apiKey": False,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": False,
                "accessTokenRequiresStore": False,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "deleteOAuthInstallation",
        }
        await self._client.request(
            method="delete",
            path=("v2", "oauth", "installation"),
            request_options=request_options,
        )
