# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

_DOMAIN_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData",
    "required": [],
    "properties": {
        "serials": {"kind": "array", "items": {"kind": "primitive", "type": "string"}},
        "delivered_files": {
            "kind": "array",
            "items": {"kind": "primitive", "type": "string", "format": "uri"},
        },
        "dynamic": {"kind": "primitive", "type": "string"},
        "manual": {"kind": "primitive", "type": "string"},
        "license_keys": {
            "kind": "array",
            "items": {"kind": "primitive", "type": "string"},
        },
        "credits_granted": {"kind": "primitive", "type": "integer"},
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData",
    "required": [],
    "properties": {
        "serials": {"kind": "array", "items": {"kind": "primitive", "type": "string"}},
        "delivered_files": {
            "kind": "array",
            "items": {"kind": "primitive", "type": "string", "format": "uri"},
        },
        "dynamic": {"kind": "primitive", "type": "string"},
        "manual": {"kind": "primitive", "type": "string"},
        "license_keys": {
            "kind": "array",
            "items": {"kind": "primitive", "type": "string"},
        },
        "credits_granted": {"kind": "primitive", "type": "integer"},
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData:
    """Get Invoice Deliverables Response Value200Application Json Property Data Item Property Deliverable Property Data model."""

    serials: list[str] | None = None
    delivered_files: list[str] | None = None
    dynamic: str | None = None
    manual: str | None = None
    license_keys: list[str] | None = None
    credits_granted: int | None = None
    """Number of credits granted by a credits deliverable."""
    additional_properties: dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                serials=data.get("serials"),
                delivered_files=data.get("delivered_files"),
                dynamic=data.get("dynamic"),
                manual=data.get("manual"),
                license_keys=data.get("license_keys"),
                credits_granted=data.get("credits_granted"),
                additional_properties=_preserve_unknown_fields(
                    data,
                    [
                        "serials",
                        "delivered_files",
                        "dynamic",
                        "manual",
                        "license_keys",
                        "credits_granted",
                    ],
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData",
                e,
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: dict[str, Any] = dict(self.additional_properties)
        if self.serials is not None:
            _domain_data["serials"] = self.serials
        if self.delivered_files is not None:
            _domain_data["delivered_files"] = self.delivered_files
        if self.dynamic is not None:
            _domain_data["dynamic"] = self.dynamic
        if self.manual is not None:
            _domain_data["manual"] = self.manual
        if self.license_keys is not None:
            _domain_data["license_keys"] = self.license_keys
        if self.credits_granted is not None:
            _domain_data["credits_granted"] = self.credits_granted
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: dict[str, Any] = dict(self.additional_properties)
        if self.serials is not None:
            result["serials"] = self.serials
        if self.delivered_files is not None:
            result["delivered_files"] = self.delivered_files
        if self.dynamic is not None:
            result["dynamic"] = self.dynamic
        if self.manual is not None:
            result["manual"] = self.manual
        if self.license_keys is not None:
            result["license_keys"] = self.license_keys
        if self.credits_granted is not None:
            result["credits_granted"] = self.credits_granted
        return result
