# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .create_course_lesson_request_application_json_property_assignment import (
    CreateCourseLessonRequestApplicationJsonPropertyAssignment,
)

UpdateCourseLessonRequestApplicationJsonPropertyAssignment: TypeAlias = (
    CreateCourseLessonRequestApplicationJsonPropertyAssignment
)
