# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from datetime import datetime
from enum import Enum
from typing import Any

from sellapp_sdk._types import (
    _format_datetime,
    _parse_datetime,
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

from .archive_wallet_bonus_tier_response_value_200_application_json_property_data_bonus_kind import (
    ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind,
)

_DOMAIN_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyData",
    "required": [
        "id",
        "minimum_top_up_cents",
        "bonus_kind",
        "fixed_bonus_cents",
        "percent_basis",
        "maximum_bonus_cents",
        "priority",
        "is_active",
        "superseded_by_id",
        "restorable",
    ],
    "properties": {
        "id": {"kind": "primitive", "type": "integer"},
        "minimum_top_up_cents": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 1, "maximum": 999999999999},
        },
        "bonus_kind": {"kind": "enum", "values": ["fixed", "percent"]},
        "fixed_bonus_cents": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 1, "maximum": 999999999999},
            },
        },
        "percent_basis": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 1, "maximum": 10000},
            },
        },
        "maximum_bonus_cents": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 1, "maximum": 999999999999},
            },
        },
        "priority": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 0, "maximum": 65535},
        },
        "is_active": {"kind": "primitive", "type": "boolean"},
        "superseded_by_id": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "integer"},
        },
        "restorable": {"kind": "primitive", "type": "boolean"},
        "created_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
        "updated_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
        "deleted_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyData",
    "required": [
        "id",
        "minimum_top_up_cents",
        "bonus_kind",
        "fixed_bonus_cents",
        "percent_basis",
        "maximum_bonus_cents",
        "priority",
        "is_active",
        "superseded_by_id",
        "restorable",
    ],
    "properties": {
        "id": {"kind": "primitive", "type": "integer"},
        "minimum_top_up_cents": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 1, "maximum": 999999999999},
        },
        "bonus_kind": {"kind": "enum", "values": ["fixed", "percent"]},
        "fixed_bonus_cents": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 1, "maximum": 999999999999},
            },
        },
        "percent_basis": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 1, "maximum": 10000},
            },
        },
        "maximum_bonus_cents": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 1, "maximum": 999999999999},
            },
        },
        "priority": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 0, "maximum": 65535},
        },
        "is_active": {"kind": "primitive", "type": "boolean"},
        "superseded_by_id": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "integer"},
        },
        "restorable": {"kind": "primitive", "type": "boolean"},
        "created_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
        "updated_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
        "deleted_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyData:
    """Archive Wallet Bonus Tier Response Value200Application Json Property Data model."""

    id: int
    minimum_top_up_cents: int
    bonus_kind: (
        ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind
    )
    fixed_bonus_cents: int | None
    percent_basis: int | None
    maximum_bonus_cents: int | None
    priority: int
    is_active: bool
    superseded_by_id: int | None
    """ID of the replacement tier, or null if this tier has not been superseded."""
    restorable: bool
    """True only when this tier is archived and has no replacement tier."""
    created_at: datetime | None = None
    updated_at: datetime | None = None
    deleted_at: datetime | None = None
    additional_properties: dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyData:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                id=data["id"],
                minimum_top_up_cents=data["minimum_top_up_cents"],
                bonus_kind=ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind(
                    data["bonus_kind"]
                ),
                fixed_bonus_cents=data["fixed_bonus_cents"],
                percent_basis=data["percent_basis"],
                maximum_bonus_cents=data["maximum_bonus_cents"],
                priority=data["priority"],
                is_active=data["is_active"],
                superseded_by_id=data["superseded_by_id"],
                restorable=data["restorable"],
                created_at=_parse_datetime(_v_created_at)
                if (_v_created_at := data.get("created_at")) is not None
                else None,
                updated_at=_parse_datetime(_v_updated_at)
                if (_v_updated_at := data.get("updated_at")) is not None
                else None,
                deleted_at=_parse_datetime(_v_deleted_at)
                if (_v_deleted_at := data.get("deleted_at")) is not None
                else None,
                additional_properties=_preserve_unknown_fields(
                    data,
                    [
                        "id",
                        "minimum_top_up_cents",
                        "bonus_kind",
                        "fixed_bonus_cents",
                        "percent_basis",
                        "maximum_bonus_cents",
                        "priority",
                        "is_active",
                        "superseded_by_id",
                        "restorable",
                        "created_at",
                        "updated_at",
                        "deleted_at",
                    ],
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyData", e
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: dict[str, Any] = dict(self.additional_properties)
        _domain_data["id"] = self.id
        _domain_data["minimum_top_up_cents"] = self.minimum_top_up_cents
        _domain_data["bonus_kind"] = self.bonus_kind
        _domain_data["fixed_bonus_cents"] = self.fixed_bonus_cents
        _domain_data["percent_basis"] = self.percent_basis
        _domain_data["maximum_bonus_cents"] = self.maximum_bonus_cents
        _domain_data["priority"] = self.priority
        _domain_data["is_active"] = self.is_active
        _domain_data["superseded_by_id"] = self.superseded_by_id
        _domain_data["restorable"] = self.restorable
        _domain_data["created_at"] = self.created_at
        _domain_data["updated_at"] = self.updated_at
        _domain_data["deleted_at"] = self.deleted_at
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: dict[str, Any] = dict(self.additional_properties)
        result["id"] = self.id
        result["minimum_top_up_cents"] = self.minimum_top_up_cents
        result["bonus_kind"] = (
            self.bonus_kind.value
            if isinstance(self.bonus_kind, Enum)
            else self.bonus_kind
        )
        if self.fixed_bonus_cents is not None:
            result["fixed_bonus_cents"] = self.fixed_bonus_cents
        else:
            result["fixed_bonus_cents"] = None
        if self.percent_basis is not None:
            result["percent_basis"] = self.percent_basis
        else:
            result["percent_basis"] = None
        if self.maximum_bonus_cents is not None:
            result["maximum_bonus_cents"] = self.maximum_bonus_cents
        else:
            result["maximum_bonus_cents"] = None
        result["priority"] = self.priority
        result["is_active"] = self.is_active
        if self.superseded_by_id is not None:
            result["superseded_by_id"] = self.superseded_by_id
        else:
            result["superseded_by_id"] = None
        result["restorable"] = self.restorable
        if self.created_at is not None:
            result["created_at"] = _format_datetime(self.created_at)
        else:
            result["created_at"] = None
        if self.updated_at is not None:
            result["updated_at"] = _format_datetime(self.updated_at)
        else:
            result["updated_at"] = None
        if self.deleted_at is not None:
            result["deleted_at"] = _format_datetime(self.deleted_at)
        else:
            result["deleted_at"] = None
        return result
