# This file is auto-generated by oagen. Do not edit.

"""Enumeration of batch create product variants request application json property resources item property deliverable property data property booking video provider values."""

from __future__ import annotations

from enum import Enum
from typing import Literal, TypeAlias


class BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider(
    str, Enum
):
    """Known values for BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider."""

    NONE = "none"
    GOOGLE_MEET = "google_meet"
    ZOOM = "zoom"

    @classmethod
    def _missing_(
        cls, value: object
    ) -> (
        BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProvider
        | None
    ):
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingVideoProviderLiteral: TypeAlias = Literal[
    "none", "google_meet", "zoom"
]
