# This file is auto-generated by oagen. Do not edit.

"""Enumeration of batch create product variants request application json property resources item property deliverable property data property booking reminder offset unit values."""

from __future__ import annotations

from enum import Enum
from typing import Literal, TypeAlias


class BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit(
    str, Enum
):
    """Known values for BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit."""

    MINUTES = "minutes"
    HOURS = "hours"
    DAYS = "days"
    WEEKS = "weeks"

    @classmethod
    def _missing_(
        cls, value: object
    ) -> (
        BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnit
        | None
    ):
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyDeliverablePropertyDataPropertyBookingReminderOffsetUnitLiteral: TypeAlias = Literal[
    "minutes", "hours", "days", "weeks"
]
