# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any, Dict, List, cast

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

from .product_faq_item import ProductFaqItem

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings",
    "required": [
        "faq",
        "video_url",
        "redirect_url",
        "product_title",
        "product_description",
    ],
    "properties": {
        "faq": {"kind": "array", "items": {"kind": "any"}},
        "video_url": {"kind": "primitive", "type": "string"},
        "redirect_url": {"kind": "primitive", "type": "string"},
        "product_title": {"kind": "primitive", "type": "string"},
        "product_description": {"kind": "primitive", "type": "string"},
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings",
    "required": [
        "faq",
        "video_url",
        "redirect_url",
        "product_title",
        "product_description",
    ],
    "properties": {
        "faq": {"kind": "array", "items": {"kind": "any"}},
        "video_url": {"kind": "primitive", "type": "string"},
        "redirect_url": {"kind": "primitive", "type": "string"},
        "product_title": {"kind": "primitive", "type": "string"},
        "product_description": {"kind": "primitive", "type": "string"},
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings:
    """Batch Create Products Response Value200Application Json Property Data Item Property Other Settings model."""

    faq: List[ProductFaqItem]
    video_url: str
    redirect_url: str
    product_title: str
    product_description: str
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                faq=[
                    ProductFaqItem.from_dict(cast(Dict[str, Any], item))
                    for item in cast(list[Any], data["faq"])
                ],
                video_url=data["video_url"],
                redirect_url=data["redirect_url"],
                product_title=data["product_title"],
                product_description=data["product_description"],
                additional_properties=_preserve_unknown_fields(
                    data,
                    [
                        "faq",
                        "video_url",
                        "redirect_url",
                        "product_title",
                        "product_description",
                    ],
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings",
                e,
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        _domain_data["faq"] = self.faq
        _domain_data["video_url"] = self.video_url
        _domain_data["redirect_url"] = self.redirect_url
        _domain_data["product_title"] = self.product_title
        _domain_data["product_description"] = self.product_description
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        result["faq"] = [item.to_dict() for item in self.faq]
        result["video_url"] = self.video_url
        result["redirect_url"] = self.redirect_url
        result["product_title"] = self.product_title
        result["product_description"] = self.product_description
        return result
