# This file is auto-generated by oagen. Do not edit.

"""Enumeration of category values."""

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional, TypeAlias


class Category(str, Enum):
    """Known values for Category."""

    DEVELOPMENT = "development"
    BUSINESS = "business"
    MARKETING = "marketing"
    DESIGN = "design"
    FINANCE = "finance"
    IT_SOFTWARE = "it-software"
    PERSONAL_DEVELOPMENT = "personal-development"
    PRODUCTIVITY = "productivity"
    OTHER = "other"
    NULL = "null"

    @classmethod
    def _missing_(cls, value: object) -> Optional[Category]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


CategoryLiteral: TypeAlias = Literal[
    "development",
    "business",
    "marketing",
    "design",
    "finance",
    "it-software",
    "personal-development",
    "productivity",
    "other",
    "null",
]
