# This file is auto-generated by oagen. Do not edit.

"""Enumeration of create webhook channel response value201application json property data allowed notifications values."""

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional, TypeAlias


class CreateWebhookChannelResponseValue201ApplicationJsonPropertyDataAllowedNotifications(
    str, Enum
):
    """Known values for CreateWebhookChannelResponseValue201ApplicationJsonPropertyDataAllowedNotifications."""

    BOOKING_CANCELLED = "booking.cancelled"
    BOOKING_RESCHEDULED = "booking.rescheduled"
    CASH_APP_PAYMENT_REQUIRES_ATTENTION = "cash_app.payment_requires_attention"
    CHARGE_COMPLETED = "charge.completed"
    CHARGE_CREATED = "charge.created"
    CHARGE_DISPUTED = "charge.disputed"
    CHARGE_PARTIAL_PAID = "charge.partial_paid"
    CHARGE_REVIEW = "charge.review"
    FEEDBACK_CREATED = "feedback.created"
    ORDER_COMPLETED = "order.completed"
    ORDER_CREATED = "order.created"
    ORDER_DISPUTED = "order.disputed"
    ORDER_MANUAL_PAYMENT_COMPLETED = "order.manual_payment_completed"
    ORDER_PAID = "order.paid"
    ORDER_PARTIAL_PAID = "order.partial_paid"
    PRODUCT_CREATED = "product.created"
    PRODUCT_TRASHED = "product.trashed"
    PRODUCT_UPDATED = "product.updated"
    SUBSCRIPTION_CANCELLED = "subscription.cancelled"
    SUBSCRIPTION_CREATED = "subscription.created"
    SUBSCRIPTION_RENEWED = "subscription.renewed"
    TICKET_MESSAGE_CREATED = "ticket_message.created"
    VARIANT_CREATED = "variant.created"
    VARIANT_SOLD_OUT = "variant.sold_out"
    VARIANT_UPDATED = "variant.updated"

    @classmethod
    def _missing_(
        cls, value: object
    ) -> Optional[
        CreateWebhookChannelResponseValue201ApplicationJsonPropertyDataAllowedNotifications
    ]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


CreateWebhookChannelResponseValue201ApplicationJsonPropertyDataAllowedNotificationsLiteral: TypeAlias = Literal[
    "booking.cancelled",
    "booking.rescheduled",
    "cash_app.payment_requires_attention",
    "charge.completed",
    "charge.created",
    "charge.disputed",
    "charge.partial_paid",
    "charge.review",
    "feedback.created",
    "order.completed",
    "order.created",
    "order.disputed",
    "order.manual_payment_completed",
    "order.paid",
    "order.partial_paid",
    "product.created",
    "product.trashed",
    "product.updated",
    "subscription.cancelled",
    "subscription.created",
    "subscription.renewed",
    "ticket_message.created",
    "variant.created",
    "variant.sold_out",
    "variant.updated",
]
