# This file is auto-generated by oagen. Do not edit.

"""Enumeration of create reward rule response value201application json property data trigger type values."""

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional, TypeAlias


class CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType(str, Enum):
    """Known values for CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType."""

    PURCHASE_COUNT = "PURCHASE_COUNT"
    TOTAL_SPENT = "TOTAL_SPENT"

    @classmethod
    def _missing_(
        cls, value: object
    ) -> Optional[
        CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerType
    ]:
        if not isinstance(value, str):
            return None
        unknown = str.__new__(cls, value)
        unknown._name_ = value.upper()
        unknown._value_ = value
        return unknown


CreateRewardRuleResponseValue201ApplicationJsonPropertyDataTriggerTypeLiteral: TypeAlias = Literal[
    "PURCHASE_COUNT", "TOTAL_SPENT"
]
