# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .sdk_list_add_on_s_parent_products_response_value_200_application_json import (
    SdkListAddOnSParentProductsResponseValue200ApplicationJson,
)

CreateInvoiceRequestApplicationJsonPropertyProductVariantsMapValuePropertyAdditionalInformation: TypeAlias = SdkListAddOnSParentProductsResponseValue200ApplicationJson
