# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any, Literal

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

_DOMAIN_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "CursorExpiredErrorFallback",
    "required": ["transport", "url"],
    "properties": {
        "transport": {"kind": "literal", "value": "cursor_polling"},
        "url": {"kind": "primitive", "type": "string", "format": "uri"},
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "CursorExpiredErrorFallback",
    "required": ["transport", "url"],
    "properties": {
        "transport": {"kind": "literal", "value": "cursor_polling"},
        "url": {"kind": "primitive", "type": "string", "format": "uri"},
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class CursorExpiredErrorFallback:
    """Cursor Expired Error Fallback model."""

    transport: Literal["cursor_polling"]
    url: str
    additional_properties: dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CursorExpiredErrorFallback:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                transport=data.get("transport", "cursor_polling"),
                url=data["url"],
                additional_properties=_preserve_unknown_fields(
                    data, ["transport", "url"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("CursorExpiredErrorFallback", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: dict[str, Any] = dict(self.additional_properties)
        _domain_data["transport"] = self.transport
        _domain_data["url"] = self.url
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: dict[str, Any] = dict(self.additional_properties)
        result["transport"] = self.transport
        result["url"] = self.url
        return result
