# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .cancel_appointment_response_value_200_application_json_property_data_status import (
    CancelAppointmentResponseValue200ApplicationJsonPropertyDataStatus,
)

GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus: TypeAlias = (
    CancelAppointmentResponseValue200ApplicationJsonPropertyDataStatus
)
__all__ = ["GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus"]
