# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .list_customer_entitlements_response_value_200_application_json_property_data_item_state import (
    ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemState,
)

ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemState: TypeAlias = ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItemState
__all__ = [
    "ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemState"
]
