# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .get_course_response_value_200_application_json_property_data_level import (
    GetCourseResponseValue200ApplicationJsonPropertyDataLevel,
)

ReplaceCourseResponseValue200ApplicationJsonPropertyDataLevel: TypeAlias = (
    GetCourseResponseValue200ApplicationJsonPropertyDataLevel
)
__all__ = ["ReplaceCourseResponseValue200ApplicationJsonPropertyDataLevel"]
