# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .sdk_get_oauth_authorization_request_response_value_400_application_json import (
    SdkGetOAuthAuthorizationRequestResponseValue400ApplicationJson,
)

SdkGetOAuthAuthorizationRequestResponseValue401ApplicationJson: TypeAlias = (
    SdkGetOAuthAuthorizationRequestResponseValue400ApplicationJson
)
