# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .create_promotion_request_application_json_property_phases_item_discount_type import (
    CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType,
)

UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType: TypeAlias = CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType
__all__ = [
    "UpdateReferralStatusResponseValue200ApplicationJsonPropertyDataPropertyCommissionType"
]
