# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from datetime import datetime
from enum import Enum
from typing import Any

from sellapp_sdk._types import (
    _format_datetime,
    _parse_datetime,
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)
from sellapp_sdk.common.models.payment_method import PaymentMethod
from sellapp_sdk.common.models.status import Status

_DOMAIN_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyOrder",
    "required": ["id", "status", "payment_method", "customer_id"],
    "properties": {
        "id": {"kind": "primitive", "type": "integer"},
        "status": {
            "kind": "nullable",
            "inner": {
                "kind": "enum",
                "values": [
                    "PENDING",
                    "REVERSED",
                    "PARTIAL",
                    "VOIDED",
                    "REFUNDED",
                    "PAID",
                    "COMPLETED",
                    "DISPUTING",
                    "REVIEW",
                    "FAILED",
                ],
            },
        },
        "payment_method": {
            "kind": "nullable",
            "inner": {
                "kind": "enum",
                "values": [
                    "AUTHNET",
                    "BTCPAY",
                    "CASHAPP",
                    "COINBASE",
                    "PADDLE",
                    "PAYDASH",
                    "PAYPAL",
                    "PAYSTACK",
                    "SQUARE",
                    "STRIPE",
                    "VENMO",
                    "NMI",
                    "MERCADO_PAGO",
                    "MOLLIE",
                    "RAZORPAY",
                    "CUSTOM_PAYMENT_METHOD",
                    "LIFI",
                    "BTC",
                    "LTC",
                    "ETH",
                    "XMR",
                    "SOL",
                    "ADA",
                    "BNB",
                    "TRX",
                    "MATIC",
                    "ETH_USDT",
                    "ETH_USDC",
                    "ETH_UNI",
                    "ETH_SHIB",
                    "ETH_DAI",
                    "BNB_USDT",
                    "BNB_USDC",
                    "TRX_USDT",
                    "TRX_USDC",
                    "SOL_USDT",
                    "SOL_USDC",
                ],
            },
        },
        "customer_id": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "integer"},
        },
        "created_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
        "updated_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyOrder",
    "required": ["id", "status", "payment_method", "customer_id"],
    "properties": {
        "id": {"kind": "primitive", "type": "integer"},
        "status": {
            "kind": "nullable",
            "inner": {
                "kind": "enum",
                "values": [
                    "PENDING",
                    "REVERSED",
                    "PARTIAL",
                    "VOIDED",
                    "REFUNDED",
                    "PAID",
                    "COMPLETED",
                    "DISPUTING",
                    "REVIEW",
                    "FAILED",
                ],
            },
        },
        "payment_method": {
            "kind": "nullable",
            "inner": {
                "kind": "enum",
                "values": [
                    "AUTHNET",
                    "BTCPAY",
                    "CASHAPP",
                    "COINBASE",
                    "PADDLE",
                    "PAYDASH",
                    "PAYPAL",
                    "PAYSTACK",
                    "SQUARE",
                    "STRIPE",
                    "VENMO",
                    "NMI",
                    "MERCADO_PAGO",
                    "MOLLIE",
                    "RAZORPAY",
                    "CUSTOM_PAYMENT_METHOD",
                    "LIFI",
                    "BTC",
                    "LTC",
                    "ETH",
                    "XMR",
                    "SOL",
                    "ADA",
                    "BNB",
                    "TRX",
                    "MATIC",
                    "ETH_USDT",
                    "ETH_USDC",
                    "ETH_UNI",
                    "ETH_SHIB",
                    "ETH_DAI",
                    "BNB_USDT",
                    "BNB_USDC",
                    "TRX_USDT",
                    "TRX_USDC",
                    "SOL_USDT",
                    "SOL_USDC",
                ],
            },
        },
        "customer_id": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "integer"},
        },
        "created_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
        "updated_at": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string", "format": "date-time"},
        },
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyOrder:
    """Get Order Line Item Response Value200Application Json Property Data Property Order model."""

    id: int
    status: Status | None
    payment_method: PaymentMethod | None
    customer_id: int | None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    additional_properties: dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyOrder:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                id=data["id"],
                status=Status(_v_status)
                if (_v_status := data["status"]) is not None
                else None,
                payment_method=PaymentMethod(_v_payment_method)
                if (_v_payment_method := data["payment_method"]) is not None
                else None,
                customer_id=data["customer_id"],
                created_at=_parse_datetime(_v_created_at)
                if (_v_created_at := data.get("created_at")) is not None
                else None,
                updated_at=_parse_datetime(_v_updated_at)
                if (_v_updated_at := data.get("updated_at")) is not None
                else None,
                additional_properties=_preserve_unknown_fields(
                    data,
                    [
                        "id",
                        "status",
                        "payment_method",
                        "customer_id",
                        "created_at",
                        "updated_at",
                    ],
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyOrder",
                e,
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: dict[str, Any] = dict(self.additional_properties)
        _domain_data["id"] = self.id
        _domain_data["status"] = self.status
        _domain_data["payment_method"] = self.payment_method
        _domain_data["customer_id"] = self.customer_id
        _domain_data["created_at"] = self.created_at
        _domain_data["updated_at"] = self.updated_at
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: dict[str, Any] = dict(self.additional_properties)
        result["id"] = self.id
        if self.status is not None:
            result["status"] = (
                self.status.value if isinstance(self.status, Enum) else self.status
            )
        else:
            result["status"] = None
        if self.payment_method is not None:
            result["payment_method"] = (
                self.payment_method.value
                if isinstance(self.payment_method, Enum)
                else self.payment_method
            )
        else:
            result["payment_method"] = None
        if self.customer_id is not None:
            result["customer_id"] = self.customer_id
        else:
            result["customer_id"] = None
        if self.created_at is not None:
            result["created_at"] = _format_datetime(self.created_at)
        else:
            result["created_at"] = None
        if self.updated_at is not None:
            result["updated_at"] = _format_datetime(self.updated_at)
        else:
            result["updated_at"] = None
        return result
