# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from enum import Enum
from typing import Any, Dict, Optional

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)
from sellapp_sdk.common.models.get_account_response_value_200_application_json_property_data_credential_type import (
    GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType,
)

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "GetAccountResponseValue200ApplicationJsonPropertyData",
    "required": ["id", "username", "email", "credential_type"],
    "properties": {
        "id": {"kind": "primitive", "type": "string"},
        "username": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string"},
        },
        "email": {"kind": "primitive", "type": "string"},
        "credential_type": {"kind": "enum", "values": ["sanctum", "oauth"]},
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "GetAccountResponseValue200ApplicationJsonPropertyData",
    "required": ["id", "username", "email", "credential_type"],
    "properties": {
        "id": {"kind": "primitive", "type": "string"},
        "username": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string"},
        },
        "email": {"kind": "primitive", "type": "string"},
        "credential_type": {"kind": "enum", "values": ["sanctum", "oauth"]},
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class GetAccountResponseValue200ApplicationJsonPropertyData:
    """Get Account Response Value200Application Json Property Data model."""

    id: str
    username: Optional[str]
    email: str
    credential_type: GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> GetAccountResponseValue200ApplicationJsonPropertyData:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                id=data["id"],
                username=data["username"],
                email=data["email"],
                credential_type=GetAccountResponseValue200ApplicationJsonPropertyDataCredentialType(
                    data["credential_type"]
                ),
                additional_properties=_preserve_unknown_fields(
                    data, ["id", "username", "email", "credential_type"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "GetAccountResponseValue200ApplicationJsonPropertyData", e
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        _domain_data["id"] = self.id
        _domain_data["username"] = self.username
        _domain_data["email"] = self.email
        _domain_data["credential_type"] = self.credential_type
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        result["id"] = self.id
        if self.username is not None:
            result["username"] = self.username
        else:
            result["username"] = None
        result["email"] = self.email
        result["credential_type"] = (
            self.credential_type.value
            if isinstance(self.credential_type, Enum)
            else self.credential_type
        )
        return result
