# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any, cast

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

from .replace_marketing_settings_request_application_json_property_abandoned_cart import (
    ReplaceMarketingSettingsRequestApplicationJsonPropertyAbandonedCart,
)

_DOMAIN_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "SdkReplaceMarketingSettingsRequestApplicationJson",
    "required": ["abandoned_cart"],
    "properties": {"abandoned_cart": {"kind": "any"}},
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "SdkReplaceMarketingSettingsRequestApplicationJson",
    "required": ["abandoned_cart"],
    "properties": {"abandoned_cart": {"kind": "any"}},
    "additionalProperties": True,
}


@dataclass(slots=True)
class SdkReplaceMarketingSettingsRequestApplicationJson:
    """Sdk Replace Marketing Settings Request Application Json model."""

    abandoned_cart: ReplaceMarketingSettingsRequestApplicationJsonPropertyAbandonedCart
    additional_properties: dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> SdkReplaceMarketingSettingsRequestApplicationJson:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                abandoned_cart=ReplaceMarketingSettingsRequestApplicationJsonPropertyAbandonedCart.from_dict(
                    cast(dict[str, Any], data["abandoned_cart"])
                ),
                additional_properties=_preserve_unknown_fields(
                    data, ["abandoned_cart"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "SdkReplaceMarketingSettingsRequestApplicationJson", e
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: dict[str, Any] = dict(self.additional_properties)
        _domain_data["abandoned_cart"] = self.abandoned_cart
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: dict[str, Any] = dict(self.additional_properties)
        result["abandoned_cart"] = self.abandoned_cart.to_dict()
        return result
