# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from enum import Enum
from typing import Any, Dict, Literal, Optional

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)
from sellapp_sdk.common.models.create_wallet_top_up_response_value_201_application_json_property_data_payment_method import (
    CreateWalletTopUpResponseValue201ApplicationJsonPropertyDataPaymentMethod,
)

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "CreateWalletTopUpResponseValue201ApplicationJsonPropertyData",
    "required": [
        "charge_id",
        "amount_cents",
        "currency",
        "checkout_url",
        "payment_method",
        "custom_payment_method_id",
    ],
    "properties": {
        "charge_id": {"kind": "primitive", "type": "integer"},
        "amount_cents": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 1, "maximum": 999999999999},
        },
        "currency": {"kind": "literal", "value": "USD"},
        "checkout_url": {"kind": "primitive", "type": "string", "format": "uri"},
        "payment_method": {
            "kind": "enum",
            "values": [
                "AUTHNET",
                "BTCPAY",
                "CASHAPP",
                "COINBASE",
                "PADDLE",
                "PAYDASH",
                "PAYPAL",
                "PAYSTACK",
                "SQUARE",
                "STRIPE",
                "VENMO",
                "NMI",
                "MERCADO_PAGO",
                "MOLLIE",
                "RAZORPAY",
                "CUSTOM_PAYMENT_METHOD",
                "LIFI",
                "BTC",
                "LTC",
                "ETH",
                "XMR",
                "SOL",
                "ADA",
                "BNB",
                "TRX",
                "MATIC",
                "ETH_USDT",
                "ETH_USDC",
                "ETH_UNI",
                "ETH_SHIB",
                "ETH_DAI",
                "BNB_USDT",
                "BNB_USDC",
                "TRX_USDT",
                "TRX_USDC",
                "SOL_USDT",
                "SOL_USDC",
            ],
        },
        "custom_payment_method_id": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "string",
                "constraints": {
                    "minLength": 26,
                    "maxLength": 26,
                    "pattern": "^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$",
                },
            },
        },
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "CreateWalletTopUpResponseValue201ApplicationJsonPropertyData",
    "required": [
        "charge_id",
        "amount_cents",
        "currency",
        "checkout_url",
        "payment_method",
        "custom_payment_method_id",
    ],
    "properties": {
        "charge_id": {"kind": "primitive", "type": "integer"},
        "amount_cents": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 1, "maximum": 999999999999},
        },
        "currency": {"kind": "literal", "value": "USD"},
        "checkout_url": {"kind": "primitive", "type": "string", "format": "uri"},
        "payment_method": {
            "kind": "enum",
            "values": [
                "AUTHNET",
                "BTCPAY",
                "CASHAPP",
                "COINBASE",
                "PADDLE",
                "PAYDASH",
                "PAYPAL",
                "PAYSTACK",
                "SQUARE",
                "STRIPE",
                "VENMO",
                "NMI",
                "MERCADO_PAGO",
                "MOLLIE",
                "RAZORPAY",
                "CUSTOM_PAYMENT_METHOD",
                "LIFI",
                "BTC",
                "LTC",
                "ETH",
                "XMR",
                "SOL",
                "ADA",
                "BNB",
                "TRX",
                "MATIC",
                "ETH_USDT",
                "ETH_USDC",
                "ETH_UNI",
                "ETH_SHIB",
                "ETH_DAI",
                "BNB_USDT",
                "BNB_USDC",
                "TRX_USDT",
                "TRX_USDC",
                "SOL_USDT",
                "SOL_USDC",
            ],
        },
        "custom_payment_method_id": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "string",
                "constraints": {
                    "minLength": 26,
                    "maxLength": 26,
                    "pattern": "^[0-7][0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{25}$",
                },
            },
        },
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class CreateWalletTopUpResponseValue201ApplicationJsonPropertyData:
    """Create Wallet Top Up Response Value201Application Json Property Data model."""

    charge_id: int
    """Use this charge ID to retrieve payment status."""
    amount_cents: int
    """Deposit in integer USD cents: 2500 means $25.00. The store's minimum and maximum top-up amounts also apply."""
    currency: Literal["USD"]
    checkout_url: str
    """Payment link to share with the customer. Use the returned URL without constructing one from the ID."""
    payment_method: (
        CreateWalletTopUpResponseValue201ApplicationJsonPropertyDataPaymentMethod
    )
    """One enabled payment gateway allowed by the store's wallet settings for USD. CUSTOM_PAYMENT_METHOD also requires custom_payment_method_id."""
    custom_payment_method_id: Optional[str]
    """Enabled custom method in this store. Required for CUSTOM_PAYMENT_METHOD; omit or use null for other gateways."""
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> CreateWalletTopUpResponseValue201ApplicationJsonPropertyData:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                charge_id=data["charge_id"],
                amount_cents=data["amount_cents"],
                currency=data.get("currency", "USD"),
                checkout_url=data["checkout_url"],
                payment_method=CreateWalletTopUpResponseValue201ApplicationJsonPropertyDataPaymentMethod(
                    data["payment_method"]
                ),
                custom_payment_method_id=data["custom_payment_method_id"],
                additional_properties=_preserve_unknown_fields(
                    data,
                    [
                        "charge_id",
                        "amount_cents",
                        "currency",
                        "checkout_url",
                        "payment_method",
                        "custom_payment_method_id",
                    ],
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "CreateWalletTopUpResponseValue201ApplicationJsonPropertyData", e
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        _domain_data["charge_id"] = self.charge_id
        _domain_data["amount_cents"] = self.amount_cents
        _domain_data["currency"] = self.currency
        _domain_data["checkout_url"] = self.checkout_url
        _domain_data["payment_method"] = self.payment_method
        _domain_data["custom_payment_method_id"] = self.custom_payment_method_id
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        result["charge_id"] = self.charge_id
        result["amount_cents"] = self.amount_cents
        result["currency"] = self.currency
        result["checkout_url"] = self.checkout_url
        result["payment_method"] = (
            self.payment_method.value
            if isinstance(self.payment_method, Enum)
            else self.payment_method
        )
        if self.custom_payment_method_id is not None:
            result["custom_payment_method_id"] = self.custom_payment_method_id
        else:
            result["custom_payment_method_id"] = None
        return result
