# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, List, Optional, Union

from .._base_client import WithRawResponse

if TYPE_CHECKING:
    from .._client import AsyncSellAppClient, SellAppClient

from .._pagination import AsyncPage, SyncPage
from .._types import NOT_GIVEN, NotGiven, RequestOptions, _validate_model
from .models import (
    ListGroupsResponseValue200ApplicationJsonPropertyDataItem,
    SdkCreateGroupResponseValue201ApplicationJson,
    SdkGetGroupResponseValue200ApplicationJson,
    SdkUpdateGroupResponseValue200ApplicationJson,
    SearchGroupsRequestApplicationJsonPropertyFiltersItem,
    SearchGroupsRequestApplicationJsonPropertyIncludesItem,
    SearchGroupsRequestApplicationJsonPropertySearch,
    SearchGroupsRequestApplicationJsonPropertySortItem,
    SearchGroupsResponseValue200ApplicationJsonPropertyDataItem,
)


class Groups:
    """Groups API resources."""

    def __init__(self, client: SellAppClient) -> None:
        self._client = client
        self.with_raw_response = WithRawResponse(self)

    def list(
        self,
        *,
        limit: Optional[int] = None,
        before: Optional[str] = None,
        after: Optional[str] = None,
        order: Optional[str] = None,
        page: Optional[int] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[ListGroupsResponseValue200ApplicationJsonPropertyDataItem]:
        """List all groups

        List your store's groups, 15 per page by default. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            limit: Number of items to return per page. Defaults to `15`.
            before: The before.
            after: The after.
            order: The order.
            page: Page number to return. Defaults to `1`.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SyncPage[ListGroupsResponseValue200ApplicationJsonPropertyDataItem]

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "listGroups",
        }
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order,
                "page": page,
            }.items()
            if v is not None
        }
        return self._client.request_page(
            method="get",
            path=("v2", "groups"),
            model=ListGroupsResponseValue200ApplicationJsonPropertyDataItem,
            params=params,
            request_options=request_options,
        )

    def create(
        self,
        *,
        title: str,
        unlisted: bool,
        order: Union[int, None, NotGiven] = NOT_GIVEN,
        product_ids: Optional[List[int]] = None,
        section_id: Union[int, None, NotGiven] = NOT_GIVEN,
        request_options: Optional[RequestOptions] = None,
    ) -> SdkCreateGroupResponseValue201ApplicationJson:
        """Create a group

        Create a group for related products. Supply product_ids and section_id to save the group, ordered product membership, and section together. The whole change rolls back if any selected product is invalid. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            title: The title.
            unlisted: The unlisted.
            order: The order.
            product_ids: Ordered IDs of published standard products in this store. Supply an empty array to remove every product. Missing, draft, or foreign products are rejected.
            section_id: Section in this store. Omit to preserve it; null removes the section.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkCreateGroupResponseValue201ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "createGroup",
        }
        body: Dict[str, Any] = {
            k: v
            for k, v in {
                "title": title,
                "unlisted": unlisted,
                "product_ids": product_ids,
            }.items()
            if v is not None
        }
        if not isinstance(order, NotGiven):
            body["order"] = order
        if not isinstance(section_id, NotGiven):
            body["section_id"] = section_id
        _validate_model(
            body,
            {
                "name": "SdkCreateGroupRequestApplicationJson",
                "required": ["title", "unlisted"],
                "properties": {
                    "title": {"kind": "primitive", "type": "string"},
                    "unlisted": {"kind": "primitive", "type": "boolean"},
                    "order": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                    "product_ids": {
                        "kind": "array",
                        "items": {"kind": "primitive", "type": "integer"},
                        "constraints": {"maxItems": 100, "uniqueItems": True},
                    },
                    "section_id": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return self._client.request(
            method="post",
            path=("v2", "groups"),
            body=body,
            model=SdkCreateGroupResponseValue201ApplicationJson,
            request_options=request_options,
        )

    def get(
        self,
        group: int,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> SdkGetGroupResponseValue200ApplicationJson:
        """Retrieve a group

        Retrieve a group by its ID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            group: The group path parameter.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkGetGroupResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "getGroup",
        }
        return self._client.request(
            method="get",
            path=("v2", "groups", str(group)),
            model=SdkGetGroupResponseValue200ApplicationJson,
            request_options=request_options,
        )

    def update(
        self,
        group: int,
        *,
        title: Optional[str] = None,
        unlisted: Optional[bool] = None,
        order: Union[int, None, NotGiven] = NOT_GIVEN,
        product_ids: Optional[List[int]] = None,
        section_id: Union[int, None, NotGiven] = NOT_GIVEN,
        request_options: Optional[RequestOptions] = None,
    ) -> SdkUpdateGroupResponseValue200ApplicationJson:
        """Update a group

        Update a group's details. Supply product_ids and section_id to save the group, ordered product membership, and section together. The whole change rolls back if any selected product is invalid. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            group: The group path parameter.
            title: The title.
            unlisted: The unlisted.
            order: The order.
            product_ids: Ordered IDs of published standard products in this store. Supply an empty array to remove every product. Missing, draft, or foreign products are rejected.
            section_id: Section in this store. Omit to preserve it; null removes the section.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkUpdateGroupResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "updateGroup",
        }
        body: Dict[str, Any] = {
            k: v
            for k, v in {
                "title": title,
                "unlisted": unlisted,
                "product_ids": product_ids,
            }.items()
            if v is not None
        }
        if not isinstance(order, NotGiven):
            body["order"] = order
        if not isinstance(section_id, NotGiven):
            body["section_id"] = section_id
        _validate_model(
            body,
            {
                "name": "SdkUpdateGroupRequestApplicationJson",
                "required": [],
                "properties": {
                    "title": {"kind": "primitive", "type": "string"},
                    "unlisted": {"kind": "primitive", "type": "boolean"},
                    "order": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                    "product_ids": {
                        "kind": "array",
                        "items": {"kind": "primitive", "type": "integer"},
                        "constraints": {"maxItems": 100, "uniqueItems": True},
                    },
                    "section_id": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return self._client.request(
            method="patch",
            path=("v2", "groups", str(group)),
            body=body,
            model=SdkUpdateGroupResponseValue200ApplicationJson,
            request_options=request_options,
        )

    def delete(
        self,
        group: int,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete a group

        Deletes a group. This will permanently delete the group and its details. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            group: The group path parameter.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "deleteGroup",
        }
        self._client.request(
            method="delete",
            path=("v2", "groups", str(group)),
            request_options=request_options,
        )

    def search(
        self,
        *,
        filters: Optional[
            List[SearchGroupsRequestApplicationJsonPropertyFiltersItem]
        ] = None,
        sort: Optional[List[SearchGroupsRequestApplicationJsonPropertySortItem]] = None,
        search: Optional[SearchGroupsRequestApplicationJsonPropertySearch] = None,
        includes: Optional[
            List[SearchGroupsRequestApplicationJsonPropertyIncludesItem]
        ] = None,
        limit: Optional[int] = None,
        before: Optional[str] = None,
        after: Optional[str] = None,
        order: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[SearchGroupsResponseValue200ApplicationJsonPropertyDataItem]:
        """Search groups

        Search groups using JSON body filters, search terms, includes, and sort instructions. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            filters: The filters.
            sort: The sort.
            search: The search.
            includes: The includes.
            limit: The limit.
            before: The before.
            after: The after.
            order: The order.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SyncPage[SearchGroupsResponseValue200ApplicationJsonPropertyDataItem]

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "searchGroups",
        }
        body: Dict[str, Any] = {
            k: v
            for k, v in {
                "filters": [item.to_dict() for item in filters]
                if filters is not None
                else None,
                "sort": [item.to_dict() for item in sort] if sort is not None else None,
                "search": search.to_dict() if search is not None else None,
                "includes": [item.to_dict() for item in includes]
                if includes is not None
                else None,
            }.items()
            if v is not None
        }
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order,
            }.items()
            if v is not None
        }
        return self._client.request_page(
            method="post",
            path=("v2", "groups", "search"),
            model=SearchGroupsResponseValue200ApplicationJsonPropertyDataItem,
            body=body,
            params=params,
            request_options=request_options,
        )


class AsyncGroups:
    """Groups API resources (async)."""

    def __init__(self, client: AsyncSellAppClient) -> None:
        self._client = client
        self.with_raw_response = WithRawResponse(self)

    async def list(
        self,
        *,
        limit: Optional[int] = None,
        before: Optional[str] = None,
        after: Optional[str] = None,
        order: Optional[str] = None,
        page: Optional[int] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncPage[ListGroupsResponseValue200ApplicationJsonPropertyDataItem]:
        """List all groups

        List your store's groups, 15 per page by default. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            limit: Number of items to return per page. Defaults to `15`.
            before: The before.
            after: The after.
            order: The order.
            page: Page number to return. Defaults to `1`.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            AsyncPage[ListGroupsResponseValue200ApplicationJsonPropertyDataItem]

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "listGroups",
        }
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order,
                "page": page,
            }.items()
            if v is not None
        }
        return await self._client.request_page(
            method="get",
            path=("v2", "groups"),
            model=ListGroupsResponseValue200ApplicationJsonPropertyDataItem,
            params=params,
            request_options=request_options,
        )

    async def create(
        self,
        *,
        title: str,
        unlisted: bool,
        order: Union[int, None, NotGiven] = NOT_GIVEN,
        product_ids: Optional[List[int]] = None,
        section_id: Union[int, None, NotGiven] = NOT_GIVEN,
        request_options: Optional[RequestOptions] = None,
    ) -> SdkCreateGroupResponseValue201ApplicationJson:
        """Create a group

        Create a group for related products. Supply product_ids and section_id to save the group, ordered product membership, and section together. The whole change rolls back if any selected product is invalid. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            title: The title.
            unlisted: The unlisted.
            order: The order.
            product_ids: Ordered IDs of published standard products in this store. Supply an empty array to remove every product. Missing, draft, or foreign products are rejected.
            section_id: Section in this store. Omit to preserve it; null removes the section.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkCreateGroupResponseValue201ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "createGroup",
        }
        body: Dict[str, Any] = {
            k: v
            for k, v in {
                "title": title,
                "unlisted": unlisted,
                "product_ids": product_ids,
            }.items()
            if v is not None
        }
        if not isinstance(order, NotGiven):
            body["order"] = order
        if not isinstance(section_id, NotGiven):
            body["section_id"] = section_id
        _validate_model(
            body,
            {
                "name": "SdkCreateGroupRequestApplicationJson",
                "required": ["title", "unlisted"],
                "properties": {
                    "title": {"kind": "primitive", "type": "string"},
                    "unlisted": {"kind": "primitive", "type": "boolean"},
                    "order": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                    "product_ids": {
                        "kind": "array",
                        "items": {"kind": "primitive", "type": "integer"},
                        "constraints": {"maxItems": 100, "uniqueItems": True},
                    },
                    "section_id": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return await self._client.request(
            method="post",
            path=("v2", "groups"),
            body=body,
            model=SdkCreateGroupResponseValue201ApplicationJson,
            request_options=request_options,
        )

    async def get(
        self,
        group: int,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> SdkGetGroupResponseValue200ApplicationJson:
        """Retrieve a group

        Retrieve a group by its ID. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            group: The group path parameter.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkGetGroupResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "getGroup",
        }
        return await self._client.request(
            method="get",
            path=("v2", "groups", str(group)),
            model=SdkGetGroupResponseValue200ApplicationJson,
            request_options=request_options,
        )

    async def update(
        self,
        group: int,
        *,
        title: Optional[str] = None,
        unlisted: Optional[bool] = None,
        order: Union[int, None, NotGiven] = NOT_GIVEN,
        product_ids: Optional[List[int]] = None,
        section_id: Union[int, None, NotGiven] = NOT_GIVEN,
        request_options: Optional[RequestOptions] = None,
    ) -> SdkUpdateGroupResponseValue200ApplicationJson:
        """Update a group

        Update a group's details. Supply product_ids and section_id to save the group, ordered product membership, and section together. The whole change rolls back if any selected product is invalid. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            group: The group path parameter.
            title: The title.
            unlisted: The unlisted.
            order: The order.
            product_ids: Ordered IDs of published standard products in this store. Supply an empty array to remove every product. Missing, draft, or foreign products are rejected.
            section_id: Section in this store. Omit to preserve it; null removes the section.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            SdkUpdateGroupResponseValue200ApplicationJson

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "updateGroup",
        }
        body: Dict[str, Any] = {
            k: v
            for k, v in {
                "title": title,
                "unlisted": unlisted,
                "product_ids": product_ids,
            }.items()
            if v is not None
        }
        if not isinstance(order, NotGiven):
            body["order"] = order
        if not isinstance(section_id, NotGiven):
            body["section_id"] = section_id
        _validate_model(
            body,
            {
                "name": "SdkUpdateGroupRequestApplicationJson",
                "required": [],
                "properties": {
                    "title": {"kind": "primitive", "type": "string"},
                    "unlisted": {"kind": "primitive", "type": "boolean"},
                    "order": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                    "product_ids": {
                        "kind": "array",
                        "items": {"kind": "primitive", "type": "integer"},
                        "constraints": {"maxItems": 100, "uniqueItems": True},
                    },
                    "section_id": {
                        "kind": "nullable",
                        "inner": {"kind": "primitive", "type": "integer"},
                    },
                },
                "additionalProperties": True,
            },
            direction="request",
            allow_unknown_enums=False,
            allow_unknown_union_variants=False,
            allow_unknown_fields=True,
        )
        return await self._client.request(
            method="patch",
            path=("v2", "groups", str(group)),
            body=body,
            model=SdkUpdateGroupResponseValue200ApplicationJson,
            request_options=request_options,
        )

    async def delete(
        self,
        group: int,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete a group

        Deletes a group. This will permanently delete the group and its details. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            group: The group path parameter.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            NotFoundError: If the resource is not found (404).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "deleteGroup",
        }
        await self._client.request(
            method="delete",
            path=("v2", "groups", str(group)),
            request_options=request_options,
        )

    async def search(
        self,
        *,
        filters: Optional[
            List[SearchGroupsRequestApplicationJsonPropertyFiltersItem]
        ] = None,
        sort: Optional[List[SearchGroupsRequestApplicationJsonPropertySortItem]] = None,
        search: Optional[SearchGroupsRequestApplicationJsonPropertySearch] = None,
        includes: Optional[
            List[SearchGroupsRequestApplicationJsonPropertyIncludesItem]
        ] = None,
        limit: Optional[int] = None,
        before: Optional[str] = None,
        after: Optional[str] = None,
        order: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncPage[SearchGroupsResponseValue200ApplicationJsonPropertyDataItem]:
        """Search groups

        Search groups using JSON body filters, search terms, includes, and sort instructions. OAuth callers use the admin grant and select a store with X-STORE. Current membership and role permissions apply to every request.

        Args:
            filters: The filters.
            sort: The sort.
            search: The search.
            includes: The includes.
            limit: The limit.
            before: The before.
            after: The after.
            order: The order.
            request_options: Per-request options. Supports extra_headers, timeout, max_retries, and base_url override.

        Returns:
            AsyncPage[SearchGroupsResponseValue200ApplicationJsonPropertyDataItem]

        Raises:
            BadRequestError: If the request is malformed (400).
            AuthenticationError: If the API key is invalid (401).
            AuthorizationError: If the request is forbidden (403).
            UnprocessableEntityError: If the request data is unprocessable (422).
            RateLimitExceededError: If rate limited (429).
            ServerError: If the server returns a 5xx error.
        """
        request_options = {
            **(request_options or {}),
            "auth": {
                "alternatives": [
                    [{"schemeName": "bearerAuth", "scopes": []}],
                    [
                        {"schemeName": "oauthAccessToken", "scopes": ["admin"]},
                        {"schemeName": "storeAuth", "scopes": []},
                    ],
                ],
                "anonymous": False,
                "apiKey": True,
                "accessToken": True,
                "customerSession": False,
                "browserSession": False,
                "clientBasic": False,
                "apiKeyRequiresStore": False,
                "apiKeyUsesStore": True,
                "accessTokenRequiresStore": True,
            },
            "server": None,
            "encoding": "json",
            "no_retry": False,
            "text_response": False,
        }
        request_options = {
            **(request_options or {}),
            "idempotency_supported": False,
            "operation_id": "searchGroups",
        }
        body: Dict[str, Any] = {
            k: v
            for k, v in {
                "filters": [item.to_dict() for item in filters]
                if filters is not None
                else None,
                "sort": [item.to_dict() for item in sort] if sort is not None else None,
                "search": search.to_dict() if search is not None else None,
                "includes": [item.to_dict() for item in includes]
                if includes is not None
                else None,
            }.items()
            if v is not None
        }
        params = {
            k: v
            for k, v in {
                "limit": limit,
                "before": before,
                "after": after,
                "order": order,
            }.items()
            if v is not None
        }
        return await self._client.request_page(
            method="post",
            path=("v2", "groups", "search"),
            model=SearchGroupsResponseValue200ApplicationJsonPropertyDataItem,
            body=body,
            params=params,
            request_options=request_options,
        )
