# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from sellapp_sdk.common.models.batch_create_product_variants_response_value_200_application_json_property_data_item import (
    BatchCreateProductVariantsResponseValue200ApplicationJsonPropertyDataItem,
)

CreateProductVariantResponseValue201ApplicationJsonPropertyData: TypeAlias = (
    BatchCreateProductVariantsResponseValue200ApplicationJsonPropertyDataItem
)
