# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .list_product_variants_response_value_200_application_json_property_data_item import (
    ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem,
)

SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem: TypeAlias = (
    ListProductVariantsResponseValue200ApplicationJsonPropertyDataItem
)
