# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from enum import Enum
from typing import Any, Dict, Optional

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)
from sellapp_sdk.common.models.update_product_variant_pricing_request_application_json_property_pricing_property_price_currency import (
    UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency,
)

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice",
    "required": [],
    "properties": {
        "price": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 0},
        },
        "currency": {
            "kind": "enum",
            "values": [
                "AUD",
                "BRL",
                "CAD",
                "CNY",
                "CZK",
                "DKK",
                "EUR",
                "GHS",
                "HKD",
                "HUF",
                "ILS",
                "INR",
                "JPY",
                "MYR",
                "MXN",
                "NGN",
                "TWD",
                "NZD",
                "NOK",
                "PHP",
                "PLN",
                "GBP",
                "RUB",
                "SGD",
                "SEK",
                "CHF",
                "THB",
                "USD",
                "ZAR",
            ],
        },
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice",
    "required": [],
    "properties": {
        "price": {
            "kind": "primitive",
            "type": "integer",
            "constraints": {"minimum": 0},
        },
        "currency": {
            "kind": "enum",
            "values": [
                "AUD",
                "BRL",
                "CAD",
                "CNY",
                "CZK",
                "DKK",
                "EUR",
                "GHS",
                "HKD",
                "HUF",
                "ILS",
                "INR",
                "JPY",
                "MYR",
                "MXN",
                "NGN",
                "TWD",
                "NZD",
                "NOK",
                "PHP",
                "PLN",
                "GBP",
                "RUB",
                "SGD",
                "SEK",
                "CHF",
                "THB",
                "USD",
                "ZAR",
            ],
        },
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice:
    """Base price in integer minor units."""

    price: Optional[int] = None
    currency: Optional[
        UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency
    ] = None
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                price=data.get("price"),
                currency=UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPriceCurrency(
                    _v_currency
                )
                if (_v_currency := data.get("currency")) is not None
                else None,
                additional_properties=_preserve_unknown_fields(
                    data, ["price", "currency"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "UpdateProductVariantPricingRequestApplicationJsonPropertyPricingPropertyPrice",
                e,
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        if self.price is not None:
            _domain_data["price"] = self.price
        if self.currency is not None:
            _domain_data["currency"] = self.currency
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        if self.price is not None:
            result["price"] = self.price
        if self.currency is not None:
            result["currency"] = (
                self.currency.value
                if isinstance(self.currency, Enum)
                else self.currency
            )
        return result
