# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from enum import Enum
from typing import Any, Dict, Optional

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)
from sellapp_sdk.common.models.get_affiliate_referral_response_value_200_application_json_property_data_property_commission_type import (
    GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommissionType,
)

_DOMAIN_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommission",
    "required": ["type", "percentage", "amount_usd_cents"],
    "properties": {
        "type": {"kind": "enum", "values": ["percentage", "fixed"]},
        "percentage": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string"},
        },
        "amount_usd_cents": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 0},
            },
        },
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: Dict[str, Any] = {
    "name": "GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommission",
    "required": ["type", "percentage", "amount_usd_cents"],
    "properties": {
        "type": {"kind": "enum", "values": ["percentage", "fixed"]},
        "percentage": {
            "kind": "nullable",
            "inner": {"kind": "primitive", "type": "string"},
        },
        "amount_usd_cents": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "integer",
                "constraints": {"minimum": 0},
            },
        },
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommission:
    """Get Affiliate Referral Response Value200Application Json Property Data Property Commission model."""

    type: GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommissionType
    percentage: Optional[str]
    """The percentage commission as a decimal string when type is percentage."""
    amount_usd_cents: Optional[int]
    """The fixed commission in integer USD cents when type is fixed."""
    additional_properties: Dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: Dict[str, Any]
    ) -> GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommission:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                type=GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommissionType(
                    data["type"]
                ),
                percentage=data["percentage"],
                amount_usd_cents=data["amount_usd_cents"],
                additional_properties=_preserve_unknown_fields(
                    data, ["type", "percentage", "amount_usd_cents"]
                ),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error(
                "GetAffiliateReferralResponseValue200ApplicationJsonPropertyDataPropertyCommission",
                e,
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: Dict[str, Any] = dict(self.additional_properties)
        _domain_data["type"] = self.type
        _domain_data["percentage"] = self.percentage
        _domain_data["amount_usd_cents"] = self.amount_usd_cents
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: Dict[str, Any] = dict(self.additional_properties)
        result["type"] = self.type.value if isinstance(self.type, Enum) else self.type
        if self.percentage is not None:
            result["percentage"] = self.percentage
        else:
            result["percentage"] = None
        if self.amount_usd_cents is not None:
            result["amount_usd_cents"] = self.amount_usd_cents
        else:
            result["amount_usd_cents"] = None
        return result
