# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from sellapp_sdk.common.models.sdk_create_fulfillment_retry_request_application_json import (
    SdkCreateFulfillmentRetryRequestApplicationJson,
)

SdkRetryOrderFulfillmentRequestApplicationJson: TypeAlias = (
    SdkCreateFulfillmentRetryRequestApplicationJson
)
