# This file is auto-generated by oagen. Do not edit.

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any

from sellapp_sdk._types import (
    _preserve_unknown_fields,
    _raise_deserialize_error,
    _validate_model,
)

_DOMAIN_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "SdkCreateOrderRefundRequestApplicationJson",
    "required": [],
    "properties": {
        "amount": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "string",
                "constraints": {"maxLength": 32},
            },
        }
    },
    "additionalProperties": True,
}
_WIRE_RUNTIME_SCHEMA: dict[str, Any] = {
    "name": "SdkCreateOrderRefundRequestApplicationJson",
    "required": [],
    "properties": {
        "amount": {
            "kind": "nullable",
            "inner": {
                "kind": "primitive",
                "type": "string",
                "constraints": {"maxLength": 32},
            },
        }
    },
    "additionalProperties": True,
}


@dataclass(slots=True)
class SdkCreateOrderRefundRequestApplicationJson:
    """Sdk Create Order Refund Request Application Json model."""

    amount: str | None = None
    """Decimal major-unit amount in the order currency, positive and no greater than remaining balance. Precision follows that currency. Omission/null/empty requests the full remaining balance."""
    additional_properties: dict[str, Any] = dataclass_field(
        default_factory=dict, repr=False
    )
    _from_response: bool = dataclass_field(default=False, repr=False, compare=False)

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> SdkCreateOrderRefundRequestApplicationJson:
        """Deserialize from a dictionary."""
        try:
            _validate_model(
                data,
                _WIRE_RUNTIME_SCHEMA,
                direction="response",
                allow_unknown_enums=True,
                allow_unknown_union_variants=True,
                allow_unknown_fields=True,
            )
            return cls(
                amount=data.get("amount"),
                additional_properties=_preserve_unknown_fields(data, ["amount"]),
                _from_response=True,
            )
        except (KeyError, ValueError) as e:
            _raise_deserialize_error("SdkCreateOrderRefundRequestApplicationJson", e)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        _domain_data: dict[str, Any] = dict(self.additional_properties)
        _domain_data["amount"] = self.amount
        _validate_model(
            _domain_data,
            _DOMAIN_RUNTIME_SCHEMA,
            direction="request",
            allow_unknown_enums=self._from_response,
            allow_unknown_union_variants=self._from_response,
            allow_unknown_fields=(self._from_response or True),
        )
        result: dict[str, Any] = dict(self.additional_properties)
        if self.amount is not None:
            result["amount"] = self.amount
        else:
            result["amount"] = None
        return result
