# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from .sdk_create_order_replacement_response_value_200_application_json import (
    SdkCreateOrderReplacementResponseValue200ApplicationJson,
)

SdkUpdateOrderStatusResponseValue200ApplicationJson: TypeAlias = (
    SdkCreateOrderReplacementResponseValue200ApplicationJson
)
