# This file is auto-generated by oagen. Do not edit.

from typing import TypeAlias

from sellapp_sdk.common.models.sdk_batch_create_coupons_response_value_200_application_json import (
    SdkBatchCreateCouponsResponseValue200ApplicationJson,
)

SdkBatchUpdateCouponsResponseValue200ApplicationJson: TypeAlias = (
    SdkBatchCreateCouponsResponseValue200ApplicationJson
)
